# ── Generated by the Frankie Compiler v1.11 ─────────────────────────
import math as _math
import sys as _sys
from frankie_stdlib import *

def basic_auth_ok_q(req, expected_user, expected_pass):
    header = (_fk_index(req.headers, 'Authorization') or _fk_index(req.headers, 'authorization'))
    if (header == None):
        return False
    if (not header.startswith('Basic ')):
        return False
    encoded = _fk_slice(header, 6, (-1), inclusive=True).strip()
    decoded = base64_decode(encoded)
    parts = decoded.split(':')
    if (len(parts) < 2):
        return False
    user = _fk_index(parts, 0)
    pass = ':'.join([str(_e) for _e in _fk_slice(parts, 1, (-1), inclusive=True)])
    return ((user == expected_user) and (pass == expected_pass))

def auth_token_create(subject, secret):
    return hmac_sign(subject, secret)

def auth_token_verify(req, secret):
    header = (_fk_index(req.headers, 'Authorization') or _fk_index(req.headers, 'authorization'))
    if (header == None):
        return None
    if (not header.startswith('Bearer ')):
        return None
    token = _fk_slice(header, 7, (-1), inclusive=True).strip()
    return hmac_verify(token, secret)

def bearer_required(req, secret):
    user = auth_token_verify(req, secret)
    if (user == None):
        halt(401, 'Unauthorized')
    return user
