# ── Generated by the Frankie Compiler v1.20.1 ─────────────────────────
import math as _math
import sys as _sys
from frankie_stdlib import *

def _blk_fn_1():
    a = [1, 2, 3]
    b = [10, 20, 30]
    assert_eq(_fk_arith('a', a, 'b', b, '+'), [11, 22, 33], 'elementwise +')
    assert_eq(_fk_arith('a', a, 'b', b, '-'), [(-9), (-18), (-27)], 'elementwise -')
    return assert_eq(_fk_arith('a', a, '2', 2, '*'), [1, 2, 3, 1, 2, 3], '* n still repeats (Python-list semantics, unchanged)')
test('vector arithmetic still elementwise (regression, unchanged)', _blk_fn_1)
def _blk_fn_2():
    m1 = [[1, 2], [3, 4]]
    m2 = [[5, 6], [7, 8]]
    assert_eq(_fk_arith('m1', m1, 'm2', m2, '+'), [[6, 8], [10, 12]], 'matrix +')
    return assert_eq(_fk_arith('m1', m1, 'm2', m2, '-'), [[(-4), (-4)], [(-4), (-4)]], 'matrix -')
test('matrix + and - are truly element-wise, not row concatenation', _blk_fn_2)
def _blk_fn_3():
    m = matrix_new(2, 3, 0)
    return assert_eq(m, [[0, 0, 0], [0, 0, 0]], '2x3 zero matrix')
test('matrix_new builds a filled rows x cols matrix', _blk_fn_3)
test('matrix_identity builds an identity matrix', lambda : assert_eq(matrix_identity(3), [[1, 0, 0], [0, 1, 0], [0, 0, 1]], '3x3 identity'))
test('matrix_shape reports rows and cols', lambda : assert_eq(matrix_shape(matrix_new(2, 5, 0)), [2, 5], 'shape'))
test('matrix_transpose swaps rows and columns', lambda : assert_eq(matrix_transpose([[1, 2, 3], [4, 5, 6]]), [[1, 4], [2, 5], [3, 6]], 'transpose'))
test('matrix_scale multiplies every element', lambda : assert_eq(matrix_scale([[1, 2], [3, 4]], 3), [[3, 6], [9, 12]], 'scale by 3'))
def _blk_fn_4():
    result = matrix_multiply([[1, 2], [3, 4]], [[5, 6], [7, 8]])
    return assert_eq(result, [[19, 22], [43, 50]], '2x2 multiply')
test('matrix_multiply does real row-by-column multiplication', _blk_fn_4)
test('matrix_multiply raises on shape mismatch', lambda : assert_raises((lambda : matrix_multiply([[1, 2]], [[1, 2]]))))
def _blk_fn_5():
    c = complex_new(3, 4)
    assert_eq(complex_real(c), 3.0, 'real part')
    assert_eq(complex_imag(c), 4.0, 'imag part')
    return assert_eq(complex_abs(c), 5.0, 'magnitude (3-4-5 triangle)')
test('complex_new and accessors', _blk_fn_5)
def _blk_fn_6():
    c1 = complex_new(3, 4)
    c2 = complex_new(1, 2)
    assert_eq(_fk_arith('c1', c1, 'c2', c2, '+'), complex_new(4, 6), 'complex +')
    return assert_eq(_fk_arith('c1', c1, 'c2', c2, '*'), complex_new((-5), 10), 'complex *')
test('complex arithmetic works via native Python complex', _blk_fn_6)
def _blk_fn_7():
    c = complex_new(3, 4)
    return assert_eq(complex_conj(c), complex_new(3, (-4)), 'conjugate')
test('complex_conj negates the imaginary part', _blk_fn_7)
def _blk_fn_8():
    c = complex_new(3, 4)
    return assert_eq(_fk_to_str(c), '(3+4i)', 'conventional math notation')
test("complex numbers print with i, not Python's j", _blk_fn_8)
def _blk_fn_9():
    assert_eq(sin(0), 0.0, 'sin(0)')
    assert_eq(cos(0), 1.0, 'cos(0)')
    assert_true((_fk_abs(_fk_arith("_fk_arith('_fk_sqrt(2)', _fk_sqrt(2), '2', 2, '**')", _fk_arith('_fk_sqrt(2)', _fk_sqrt(2), '2', 2, '**'), '2', 2, '-')) < 0.0001), 'sqrt(2) ** 2 ≈ 2')
    assert_true((_fk_abs(_fk_arith('PI', PI, '3.14159', 3.14159, '-')) < 0.001), 'PI constant')
    return assert_true((_fk_abs(_fk_arith('E', E, '2.71828', 2.71828, '-')) < 0.001), 'E constant')
test('trig and constants', _blk_fn_9)
def _blk_fn_10():
    assert_true((_fk_abs(_fk_arith('log(exp(1))', log(exp(1)), '1', 1, '-')) < 0.0001), 'log(exp(1)) ≈ 1')
    assert_eq(log(8, 2), 3.0, 'log base 2 of 8')
    assert_eq(log10(1000), 3.0, 'log10')
    return assert_eq(log2(8), 3.0, 'log2')
test('exp and log are inverses', _blk_fn_10)
def _blk_fn_11():
    assert_eq(factorial(5), 120, '5!')
    assert_eq(factorial(0), 1, '0! = 1')
    assert_eq(gcd(12, 18), 6, 'gcd')
    return assert_eq(lcm(4, 6), 12, 'lcm')
test('factorial, gcd, lcm', _blk_fn_11)
test('factorial raises on negative input', lambda : assert_raises((lambda : factorial((-1)))))
def _blk_fn_12():
    log = []
    try:
        while True:
            try:
                i = 0
                while True:
                    i = _fk_arith('i', i, '1', 1, '+')
                    if (i > 2):
                        raise _FkLoopBreak('outer')
                    (_fk_list_push(log, i))
                (_fk_list_push(log, 'should not reach here'))
            except _FkLoopContinue as _fk_lc:
                if _fk_lc.label != 'outer': raise
    except _FkLoopBreak as _fk_lb:
        if _fk_lb.label != 'outer': raise
    return assert_eq(log, [1, 2], 'inner ran twice, outer body never resumed')
test('break :label exits the labeled outer loop from a nested unlabeled loop', _blk_fn_12)
def _blk_fn_13():
    log = []
    i = 0
    try:
        while (i < 3):
            try:
                i = _fk_arith('i', i, '1', 1, '+')
                j = 0
                while (j < 3):
                    j = _fk_arith('j', j, '1', 1, '+')
                    if (j == 2):
                        raise _FkLoopContinue('outer')
                    (_fk_list_push(log, [i, j]))
                (_fk_list_push(log, 'unreached'))
            except _FkLoopContinue as _fk_lc:
                if _fk_lc.label != 'outer': raise
    except _FkLoopBreak as _fk_lb:
        if _fk_lb.label != 'outer': raise
    return assert_eq(log, [[1, 1], [2, 1], [3, 1]], 'next :outer skips the rest of both loops each time')
test('next :label skips to the next iteration of the labeled outer loop', _blk_fn_13)
def _blk_fn_14():
    log = []
    try:
        for x in [1, 2, 3]:
            try:
                for y in [1, 2, 3]:
                    if ((x == 2) and (y == 2)):
                        raise _FkLoopBreak('outer')
                    (_fk_list_push(log, [x, y]))
            except _FkLoopContinue as _fk_lc:
                if _fk_lc.label != 'outer': raise
    except _FkLoopBreak as _fk_lb:
        if _fk_lb.label != 'outer': raise
    return assert_eq(log, [[1, 1], [1, 2], [1, 3], [2, 1]], 'escapes both for loops via label')
test('labeled for loops work the same way', _blk_fn_14)
def _blk_fn_15():
    hits = 0
    try:
        while True:
            try:
                try:
                    while True:
                        try:
                            while True:
                                hits = _fk_arith('hits', hits, '1', 1, '+')
                                raise _FkLoopBreak('a')
                        except _FkLoopContinue as _fk_lc:
                            if _fk_lc.label != 'b': raise
                except _FkLoopBreak as _fk_lb:
                    if _fk_lb.label != 'b': raise
            except _FkLoopContinue as _fk_lc:
                if _fk_lc.label != 'a': raise
    except _FkLoopBreak as _fk_lb:
        if _fk_lb.label != 'a': raise
    return assert_eq(hits, 1, 'only ran once — escaped all three loops immediately')
test('triple nesting: innermost break can target the outermost label', _blk_fn_15)
def _blk_fn_16():
    log = []
    i = 0
    while (i < 5):
        i = _fk_arith('i', i, '1', 1, '+')
        if (i == 2):
            continue
        if (i == 4):
            _fk_break_val = None
            break
        (_fk_list_push(log, i))
    return assert_eq(log, [1, 3], 'regression: ordinary break/next still work')
test('plain unlabeled break/next are completely unaffected', _blk_fn_16)
def _blk_fn_17():
    log = []
    while True:
        (_fk_list_push(log, 'before'))
        _fk_break_val = 'some return value'
        break
    return assert_eq(log, ['before'], 'loop actually exited, not swallowed by label matching')
test('break with a plain string value is NOT mistaken for a label', _blk_fn_17)
def _blk_fn_18():
    status = 'pending'
    assert_eq(status, 'pending', 'symbol is still just a string value')
    h = {'role': 'admin'}
    return assert_eq(_fk_index(h, 'role'), 'admin', 'symbol as a hash value')
test(':symbol still works as an ordinary value everywhere else', _blk_fn_18)
def _blk_fn_19():
    _each_recv_20 = [1, 2, 3, 4, 5]
    for n in _each_recv_20:
        if (n == 3):
            _fk_break_val = _fk_arith('n', n, '10', 10, '*')
            break
    else:
        _fk_break_val = _each_recv_20
    _each_result_21 = _fk_break_val
    result = _each_result_21
    return assert_eq(result, 30, "language/loops.md's exact documented example")
test('break value from .each, assigned, matches the documented example', _blk_fn_19)
def _blk_fn_22():
    seen = []
    _each_recv_23 = [1, 2, 3]
    for n in _each_recv_23:
        (_fk_list_push(seen, n))
    else:
        _fk_break_val = _each_recv_23
    _each_result_24 = _fk_break_val
    result = _each_result_24
    assert_eq(seen, [1, 2, 3], 'block still ran normally')
    return assert_eq(result, [1, 2, 3], 'unbroken .each returns the receiver')
test('plain .each with no break, assigned, returns the receiver (Ruby convention)', _blk_fn_22)
def _blk_fn_25():
    _each_recv_26 = [1, 2, 3, 4, 5]
    for n in _each_recv_26:
        if (n == 2):
            _fk_break_val = 99
            break
    else:
        _fk_break_val = _each_recv_26
    _each_result_27 = _fk_break_val
    first = _each_result_27
    assert_eq(first, 99, 'break value captured correctly')
    _each_recv_28 = [1, 2, 3, 4, 5]
    for n in _each_recv_28:
        if (n == 2):
            _fk_break_val = None
            break
    else:
        _fk_break_val = _each_recv_28
    _each_result_29 = _fk_break_val
    second = _each_result_29
    return assert_eq(second, None, 'bare break gives nil, not leftover state from the previous .each')
test('bare break (no value) from .each, assigned, gives nil — not a stale value', _blk_fn_25)
def _blk_fn_30():
    log = []
    _each_recv_31 = [1, 2, 3]
    for n in _each_recv_31:
        (_fk_list_push(log, n))
    else:
        _fk_break_val = _each_recv_31
    _each_result_32 = _fk_break_val
    _each_result_32
    return assert_eq(log, [1, 2, 3], 'statement-form .each unaffected by the expression-form fix')
test('.each assigned still runs correctly when used as a bare statement (no regression)', _blk_fn_30)
def _blk_fn_33():
    config = {'a': 1, 'b': 2, 'c': 3}
    _each_recv_34 = config
    for k, v in (_each_recv_34.items() if isinstance(_each_recv_34, dict) else enumerate(_each_recv_34)):
        if (v == 2):
            _fk_break_val = f"{_fk_to_str(k)}={_fk_to_str(v)}"
            break
    else:
        _fk_break_val = _each_recv_34
    _each_result_35 = _fk_break_val
    result = _each_result_35
    return assert_eq(result, 'b=2', 'hash .each also supports break value when assigned')
test('hash .each with break value', _blk_fn_33)
def _blk_fn_36():
    _each_recv_37 = ['a', 'b', 'c']
    for i, v in enumerate(_each_recv_37):
        if (i == 1):
            _fk_break_val = f"{_fk_to_str(i)}:{_fk_to_str(v)}"
            break
    else:
        _fk_break_val = _each_recv_37
    _each_result_38 = _fk_break_val
    result = _each_result_38
    return assert_eq(result, '1:b', 'each_with_index shares the same fix as each')
test('each_with_index with break value, assigned', _blk_fn_36)
def _blk_fn_39():
    inner_log = []
    _each_recv_40 = [1, 2]
    for a in _each_recv_40:
        _each_recv_42 = [10, 20, 30]
        for b in _each_recv_42:
            if (b == 20):
                _fk_break_val = b
                break
        else:
            _fk_break_val = _each_recv_42
        _each_result_43 = _fk_break_val
        inner_result = _each_result_43
        (_fk_list_push(inner_log, inner_result))
        if (a == 2):
            _fk_break_val = _fk_arith('a', a, '100', 100, '*')
            break
    else:
        _fk_break_val = _each_recv_40
    _each_result_41 = _fk_break_val
    outer_result = _each_result_41
    assert_eq(inner_log, [20, 20], 'inner .each broke with the right value both times')
    return assert_eq(outer_result, 200, 'outer .each broke with its own value, unaffected by inner')
test("nested .each calls with break value don't collide (each gets its own temp vars)", _blk_fn_39)
def product(name, price=5.0, discount=1):
    return f"{_fk_to_str(name)} costs ${_fk_to_str(price)}, discount {_fk_to_str(discount)}"

test('type annotation + default together: default is used when omitted', lambda : assert_eq(product('Eggs'), 'Eggs costs $5.0, discount 1', 'both defaults applied'))
test('type annotation + default together: explicit args override the defaults', lambda : assert_eq(product('Bread', 3.0, 2), 'Bread costs $3.0, discount 2', 'explicit args win'))
test('type annotation + default together: partial override', lambda : assert_eq(product('Milk', 6.0), 'Milk costs $6.0, discount 1', 'price overridden, discount defaulted'))
def _blk_fn_44():
    def area(r):
        return _fk_arith("_fk_arith('PI', PI, 'r', r, '*')", _fk_arith('PI', PI, 'r', r, '*'), 'r', r, '*')

    return assert_approx_eq(area(2.0), 12.566370614359172, 1e-07, 'annotation without default, unchanged')
test('annotation-only params (no default) still work — regression', _blk_fn_44)
def _blk_fn_45():
    def greet(name, greeting='Hello'):
        return f"{_fk_to_str(greeting)}, {_fk_to_str(name)}!"

    return assert_eq(greet('Blag'), 'Hello, Blag!', 'default without annotation, unchanged')
test('default-only params (no annotation) still work — regression', _blk_fn_45)
def _blk_fn_46():
    def connect(host, port=5432, ssl=True):
        return f"{_fk_to_str(host)}:{_fk_to_str(port)} ssl={_fk_to_str(ssl)}"

    return assert_eq(connect('localhost'), 'localhost:5432 ssl=true', 'keyword-style default, unchanged')
test('keyword-style default (name: value, no type) still works — regression', _blk_fn_46)