"""
Frankie Code Generator — Translates Frankie AST into executable Python source code.
"""

import keyword
import textwrap
from .ast_nodes import *

# Python keywords that cannot be used as identifiers in generated code.
# We append '_' to any Frankie name that collides with one of these.
_PY_KEYWORDS = frozenset(keyword.kwlist)

def _py_safe(name: str) -> str:
    """Sanitise a Frankie identifier for use as a Python name.

    Applies standard Frankie → Python transforms first (?→_q, !→_bang),
    then appends '_' if the result is a Python reserved keyword.
    """
    name = name.replace('?', '_q').replace('!', '_bang')
    if name in _PY_KEYWORDS:
        name = name + '_'
    return name


def _is_times_block_call(node) -> bool:
    """True for `N.times do ... end` (a MethodCall with .method == 'times')
    — this form emits a Python `for` loop as a side effect (via
    CodeGen._gen_times / CodeGen.emit) and hands back an empty string as
    its "value", so it is not really an expression at all. A block whose
    only statement is one of these can't be safely inlined as
    `lambda: <expr>` (the for-loop would spill out to the wrong place and
    the lambda body would be empty) — it must go through the full
    statement-based helper-function path instead, same as real control
    flow like if/while/case."""
    return (isinstance(node, MethodCall) and node.block is not None
            and node.method == 'times')


# Built-in function names (mapped from Frankie → Python/stdlib)
BUILTINS = {
    'sum', 'mean', 'min', 'max', 'abs', 'sqrt', 'floor', 'ceil',
    'length', 'vec', 'to_int', 'to_float', 'to_str', 'range_vec',
    'print_val', 'puts_val', 'round',
}

INDENT = "    "


class CodeGenError(Exception):
    pass


class CodeGen:
    def __init__(self):
        self.output = []
        self.indent_level = 0
        self._temp_counter = 0
        # v1.17: map of generated Python line number → .fk source line number.
        # Used by the runtime error handler for accurate tracebacks.
        self.line_map = {}
        self._cur_src_line = None

    def temp_var(self, prefix='_fk'):
        self._temp_counter += 1
        return f"{prefix}_{self._temp_counter}"

    def emit(self, line=""):
        if line:
            self.output.append(INDENT * self.indent_level + line)
        else:
            self.output.append("")
        if self._cur_src_line is not None:
            self.line_map[len(self.output)] = self._cur_src_line

    def indent(self):
        self.indent_level += 1

    def dedent(self):
        self.indent_level -= 1

    def generate(self, program: Program, repl_mode: bool = False) -> str:
        if not repl_mode:
            try:
                # Lazy import: frankiec.py imports compiler.codegen at module
                # load time, so importing frankiec back here at call time
                # (after both modules have finished loading) is safe — a
                # top-level import would be circular.
                from frankiec import FRANKIE_VERSION
            except ImportError:
                FRANKIE_VERSION = "1.22.0"
            self.emit(f"# ── Generated by the Frankie Compiler v{FRANKIE_VERSION} ─────────────────────────")
            self.emit("import math as _math")
            self.emit("import sys as _sys")
            self.emit("from frankie_stdlib import *")
            self.emit("")
        for node in program.body:
            self.gen_stmt(node)
        return "\n".join(self.output)

    # ─── Statements ──────────────────────────────────────────────────────────

    def _touch_line(self, node):
        """Update the current source line from a node's parser annotation."""
        src = getattr(node, '_src_line', None)
        if src is not None:
            self._cur_src_line = src

    def gen_stmt(self, node: Node):
        self._touch_line(node)
        if isinstance(node, FuncDef):
            self.gen_func_def(node)
        elif isinstance(node, IfStmt):
            self.gen_if(node)
        elif isinstance(node, UnlessStmt):
            self.gen_unless(node)
        elif isinstance(node, WhileStmt):
            self.gen_while(node)
        elif isinstance(node, UntilStmt):
            self.gen_until(node)
        elif isinstance(node, DoWhileStmt):
            self.gen_do_while(node)
        elif isinstance(node, ForInStmt):
            self.gen_for_in(node)
        elif isinstance(node, ReturnStmt):
            self.gen_return(node)
        elif isinstance(node, PrintStmt):
            self.gen_print(node)
        elif isinstance(node, DebugPrint):
            val = self.gen_expr(node.value)
            self.emit(f"_fk_debug({val})")
        elif isinstance(node, PostfixIf):
            self.gen_postfix_if(node)
        elif isinstance(node, Assign):
            self.gen_assign(node)
        elif isinstance(node, CompoundAssign):
            self.gen_compound_assign(node)
        elif isinstance(node, IndexCompoundAssign):
            self.gen_index_compound_assign(node)
        elif isinstance(node, IndexAssign):
            target = self.gen_expr(node.target)
            index = self.gen_expr(node.index)
            value = self.gen_expr(node.value)
            self.emit(f"{target}[{index}] = {value}")
        elif isinstance(node, MethodCall):
            # Statement-level method call (e.g. loop side effects)
            expr = self.gen_method_call(node)
            if expr:
                self.emit(expr)
        elif isinstance(node, SafeNavCall):
            expr = self.gen_safe_nav_call(node)
            if expr:
                self.emit(expr)
        elif isinstance(node, PipeOp):
            expr = self.gen_pipe(node)
            self.emit(expr)
        elif isinstance(node, BeginRescue):
            self.gen_begin_rescue(node)
        elif isinstance(node, RaiseStmt):
            self.gen_raise(node)
        elif isinstance(node, RequireStmt):
            self.gen_require(node)
        elif isinstance(node, StitchStmt):
            self.gen_stitch(node)
        elif isinstance(node, CaseStmt):
            self.gen_case(node)
        elif isinstance(node, DestructAssign):
            self.gen_destruct_assign(node)
        elif isinstance(node, NextStmt):
            self.gen_next(node)
        elif isinstance(node, BreakStmt):
            self.gen_break(node)
        elif isinstance(node, ConstAssign):
            self.gen_const_assign(node)
        elif isinstance(node, RecordDef):
            self.gen_record_def(node)
        elif isinstance(node, SpawnBlock):
            self.gen_spawn(node)
        elif isinstance(node, TimeoutBlock):
            self.gen_timeout(node)
        elif isinstance(node, HashDestructAssign):
            self.gen_hash_destruct_assign(node)
        elif isinstance(node, LoopStmt):
            self.gen_loop(node)
        elif isinstance(node, OrAssign):
            self.gen_or_assign(node)
        elif isinstance(node, ErrorDef):
            self.gen_error_def(node)
        elif isinstance(node, ImportStmt):
            self.gen_import(node)
        elif isinstance(node, EnumDef):
            self.gen_enum_def(node)
        elif isinstance(node, BreakpointStmt):
            line = self._cur_src_line if self._cur_src_line is not None else 0
            self.emit(f"_fk_breakpoint(__file__, {line}, globals(), locals())")
        elif isinstance(node, FuncCall):
            # FuncCall used as statement (may have a block e.g. times(5) do...)
            expr = self.gen_func_call(node)
            if expr:
                self.emit(expr)
        else:
            # Expression used as statement
            expr = self.gen_expr(node)
            self.emit(expr)

    def gen_body(self, body):
        if not body:
            self.emit("pass")
            return
        for stmt in body:
            self.gen_stmt(stmt)

    # ─── Functions ───────────────────────────────────────────────────────────

    def gen_func_def(self, node: FuncDef):
        py_name = _py_safe(node.name)
        param_parts = []
        for i, pname in enumerate(node.params):
            safe_pname = _py_safe(pname)
            default = node.defaults[i] if i < len(node.defaults) else None
            if default is not None:
                param_parts.append(f"{safe_pname}={self.gen_expr(default)}")
            else:
                param_parts.append(safe_pname)
        params = ", ".join(param_parts)
        self.emit(f"def {py_name}({params}):")
        self.indent()
        self._gen_body_implicit_return(node.body)
        self.dedent()
        self.emit()

    def _gen_body_implicit_return(self, body):
        """Emit a function body with implicit return on the last expression.

        If the last statement is an if/unless/case, we recurse into each
        branch so the branch-trailing expression becomes the return value.
        Assignments, loops, print statements and explicit returns are left
        as-is — they implicitly return nil.
        """
        _PURE_STMT = (WhileStmt, UntilStmt, DoWhileStmt, ForInStmt,
                      PrintStmt, DebugPrint, RequireStmt, StitchStmt, NextStmt,
                      BreakStmt, RecordDef, FuncDef,
                      Assign, CompoundAssign, IndexAssign,
                      IndexCompoundAssign, DestructAssign, ConstAssign,
                      PostfixIf, LoopStmt, OrAssign,
                      RaiseStmt, ErrorDef, ImportStmt,
                      EnumDef, BreakpointStmt)
        if not body:
            self.emit("pass")
            return
        for stmt in body[:-1]:
            self.gen_stmt(stmt)
        last = body[-1]
        self._touch_line(last)

        # Explicit return — emit as-is
        if isinstance(last, ReturnStmt):
            self.gen_stmt(last)
        # Pure statements — emit normally (return nil implicitly)
        elif isinstance(last, _PURE_STMT):
            self.gen_stmt(last)
        # if/unless — recurse into each branch's last expression
        elif isinstance(last, IfStmt):
            self._gen_if_implicit_return(last)
        elif isinstance(last, UnlessStmt):
            self._gen_unless_implicit_return(last)
        elif isinstance(last, CaseStmt):
            self._gen_case_implicit_return(last)
        elif isinstance(last, BeginRescue):
            self._gen_begin_rescue_implicit_return(last)
        else:
            # Expression — implicit return
            expr = self.gen_expr(last)
            self.emit(f"return {expr}")

    def _gen_if_implicit_return(self, node: IfStmt):
        """Emit an if statement where each branch tail is implicitly returned."""
        cond = self.gen_expr(node.condition)
        self.emit(f"if {cond}:")
        self.indent()
        self._gen_body_implicit_return(node.then_body)
        self.dedent()
        for ec, eb in node.elsif_clauses:
            self.emit(f"elif {self.gen_expr(ec)}:")
            self.indent()
            self._gen_body_implicit_return(eb)
            self.dedent()
        if node.else_body is not None:
            self.emit("else:")
            self.indent()
            self._gen_body_implicit_return(node.else_body)
            self.dedent()
        else:
            # No else branch — return None implicitly
            self.emit("else:")
            self.indent()
            self.emit("return None")
            self.dedent()

    def _gen_unless_implicit_return(self, node: UnlessStmt):
        """Emit an unless statement where each branch tail is implicitly returned."""
        cond = self.gen_expr(node.condition)
        self.emit(f"if not ({cond}):")
        self.indent()
        self._gen_body_implicit_return(node.then_body)
        self.dedent()
        if node.else_body:
            self.emit("else:")
            self.indent()
            self._gen_body_implicit_return(node.else_body)
            self.dedent()
        else:
            self.emit("else:")
            self.indent()
            self.emit("return None")
            self.dedent()

    def _gen_begin_rescue_implicit_return(self, node: 'BeginRescue'):
        """Emit a begin/rescue where the try body's tail and each rescue
        clause's tail are implicitly returned, mirroring if/case. The
        ensure/finally body (if any) is emitted as-is — it's cleanup code,
        not a value producer, and Python's finally already runs before any
        return in try/except takes effect."""
        self.emit("try:")
        self.indent()
        self._gen_body_implicit_return(node.body)
        self.dedent()
        clauses = node.rescue_clauses
        for clause in clauses:
            if clause.error_type is None:
                exc_class = 'Exception'
            else:
                # v1.17: resolved at runtime so user-defined error types
                # (error TimeoutError) take precedence over builtins
                exc_class = f"_fk_exc({clause.error_type!r})"
            tmp = clause.rescue_var or '_fk_err'
            self.emit(f"except {exc_class} as {tmp}:")
            self.indent()
            if clause.body:
                if clause.rescue_var:
                    self.emit(f"{clause.rescue_var} = str({clause.rescue_var})")
                self._gen_body_implicit_return(clause.body)
            else:
                self.emit("pass")
            self.dedent()
        if node.ensure_body:
            self.emit("finally:")
            self.indent()
            self.gen_body(node.ensure_body)
            self.dedent()

    def _case_cond(self, subj_tmp: str, v: Node) -> str:
        """Build one when-clause condition against the case subject.
        Hash literals shape-match; range literals test membership (v1.17)."""
        if isinstance(v, HashLiteral):
            return f"_fk_shape_match({subj_tmp}, {self.gen_expr(v)})"
        if isinstance(v, RangeLiteral):
            return f"({subj_tmp} in {self.gen_expr(v)})"
        return f"({subj_tmp} == {self.gen_expr(v)})"

    def _gen_case_implicit_return(self, node: CaseStmt):
        """Emit a case statement where each when/else branch tail is implicitly returned."""
        if node.subject is not None:
            subj = self.gen_expr(node.subject)
            subj_tmp = self.temp_var("_case")
            self.emit(f"{subj_tmp} = {subj}")
        first = True
        for values, body in node.when_clauses:
            if node.subject is not None:
                cond = " or ".join(self._case_cond(subj_tmp, v) for v in values)
            else:
                cond = " or ".join(self.gen_expr(v) for v in values)
            kw = "if" if first else "elif"
            self.emit(f"{kw} {cond}:")
            self.indent()
            self._gen_body_implicit_return(body)
            self.dedent()
            first = False
        if node.else_body is not None:
            self.emit("else:")
            self.indent()
            self._gen_body_implicit_return(node.else_body)
            self.dedent()
        else:
            self.emit("else:")
            self.indent()
            self.emit("return None")
            self.dedent()

    # ─── Control Flow ────────────────────────────────────────────────────────

    def gen_if(self, node: IfStmt):
        cond = self.gen_expr(node.condition)
        self.emit(f"if {cond}:")
        self.indent()
        self.gen_body(node.then_body)
        self.dedent()
        for ec, eb in node.elsif_clauses:
            ec_expr = self.gen_expr(ec)
            self.emit(f"elif {ec_expr}:")
            self.indent()
            self.gen_body(eb)
            self.dedent()
        if node.else_body is not None:
            self.emit("else:")
            self.indent()
            self.gen_body(node.else_body)
            self.dedent()

    def gen_unless(self, node: UnlessStmt):
        cond = self.gen_expr(node.condition)
        self.emit(f"if not ({cond}):")
        self.indent()
        self.gen_body(node.then_body)
        self.dedent()
        if node.else_body:
            self.emit("else:")
            self.indent()
            self.gen_body(node.else_body)
            self.dedent()

    def _gen_loop_with_header(self, header_line: str, body, label):
        """Emit a loop given its Python header line ('while cond:', 'for x in y:', ...)
        and body. v1.22: if `label` is set, wrap it so `break :label` / `next :label`
        (raised anywhere inside, including from nested unlabeled loops) can target
        this exact loop — Python has no native labeled break/continue, so this uses
        two exception types that re-raise on a non-matching label, letting them keep
        propagating outward to whichever loop actually owns that label."""
        if label is None:
            self.emit(header_line)
            self.indent()
            self.gen_body(body)
            self.dedent()
            return
        self.emit("try:")
        self.indent()
        self.emit(header_line)
        self.indent()
        self.emit("try:")
        self.indent()
        self.gen_body(body)
        self.dedent()
        self.emit("except _FkLoopContinue as _fk_lc:")
        self.indent()
        self.emit(f"if _fk_lc.label != {label!r}: raise")
        self.dedent()
        self.dedent()  # close the loop's own body scope
        self.dedent()  # close the outer try's body scope
        self.emit("except _FkLoopBreak as _fk_lb:")
        self.indent()
        self.emit(f"if _fk_lb.label != {label!r}: raise")
        self.dedent()

    def gen_while(self, node: WhileStmt):
        cond = self.gen_expr(node.condition)
        self._gen_loop_with_header(f"while {cond}:", node.body, node.label)

    def gen_until(self, node: UntilStmt):
        cond = self.gen_expr(node.condition)
        self._gen_loop_with_header(f"while not ({cond}):", node.body, node.label)

    def gen_do_while(self, node: DoWhileStmt):
        self.emit("while True:")
        self.indent()
        self.gen_body(node.body)
        cond = self.gen_expr(node.condition)
        self.emit(f"if not ({cond}): break")
        self.dedent()

    def gen_for_in(self, node: ForInStmt):
        iterable = self.gen_expr(node.iterable)
        self._gen_loop_with_header(f"for {node.var} in {iterable}:", node.body, node.label)

    def gen_loop(self, node: 'LoopStmt'):
        self._gen_loop_with_header("while True:", node.body, node.label)

    def gen_or_assign(self, node: 'OrAssign'):
        py_name = _py_safe(node.name)
        val = self.gen_expr(node.value)
        # x ||= val  →  x = x if (x is not None and x is not False) else val
        # Matches Ruby semantics: nil and false are both falsy triggers
        self.emit(f"{py_name} = ({py_name} if ({py_name} is not None and {py_name} is not False) else {val})")

    def gen_return(self, node: ReturnStmt):
        if node.value is None:
            self.emit("return")
        else:
            val = self.gen_expr(node.value)
            self.emit(f"return {val}")

    def gen_print(self, node: PrintStmt):
        val = self.gen_expr(node.value)
        if node.newline:
            self.emit(f"print(_fk_to_str({val}))")
        else:
            self.emit(f"print(_fk_to_str({val}), end='')")

    def gen_postfix_if(self, node: PostfixIf):
        cond = self.gen_expr(node.condition)
        if node.negated:
            self.emit(f"if not ({cond}):")
        else:
            self.emit(f"if {cond}:")
        self.indent()
        self.gen_stmt(node.stmt)
        self.dedent()

    def gen_assign(self, node: Assign):
        val = self.gen_expr(node.value)
        py_name = _py_safe(node.name)
        self.emit(f"{py_name} = {val}")

    def gen_compound_assign(self, node):
        val = self.gen_expr(node.value)
        # Evaluate the RHS into a temp exactly once — {val} may contain a
        # function call or other side-effecting expression, and embedding it
        # twice below (once in repr(), once bare) would otherwise execute it
        # twice (with exponential blowup for recursive calls).
        tmp = self.temp_var("_ca")
        py_name = _py_safe(node.name)
        self.emit(f"{tmp} = {val}")
        self.emit(f"{py_name} = _fk_arith(repr({py_name}), {py_name}, repr({tmp}), {tmp}, '{node.op}')")

    def gen_index_compound_assign(self, node):
        target = self.gen_expr(node.target)
        idx = self.gen_expr(node.index)
        val = self.gen_expr(node.value)
        # Same single-evaluation guarantee as gen_compound_assign, extended to
        # the target and index expressions, which were previously each
        # duplicated across the emitted line too.
        tgt_tmp = self.temp_var("_cat")
        idx_tmp = self.temp_var("_cai")
        val_tmp = self.temp_var("_cav")
        self.emit(f"{tgt_tmp} = {target}")
        self.emit(f"{idx_tmp} = _fk_index_key({idx})")
        self.emit(f"{val_tmp} = {val}")
        self.emit(f"{tgt_tmp}[{idx_tmp}] = _fk_arith(repr({tgt_tmp}[{idx_tmp}]), {tgt_tmp}[{idx_tmp}], repr({val_tmp}), {val_tmp}, '{node.op}')")

    # ─── Expressions ─────────────────────────────────────────────────────────

    def gen_expr(self, node: Node) -> str:
        if isinstance(node, IntLiteral):
            return str(node.value)
        if isinstance(node, FloatLiteral):
            return repr(node.value)
        if isinstance(node, BoolLiteral):
            return "True" if node.value else "False"
        if isinstance(node, NilLiteral):
            return "None"
        if isinstance(node, StringLiteral):
            return self.gen_string(node)
        if isinstance(node, Identifier):
            return _py_safe(node.name)
        if isinstance(node, VectorLiteral):
            elems = ", ".join(self.gen_expr(e) for e in node.elements)
            return f"[{elems}]"
        if isinstance(node, HashLiteral):
            pairs = ", ".join(
                f"{self.gen_expr(k)}: {self.gen_expr(v)}"
                for k, v in node.pairs
            )
            return "{" + pairs + "}"
        if isinstance(node, RangeLiteral):
            s = self.gen_expr(node.start)
            e = self.gen_expr(node.end)
            if node.inclusive:
                return f"range({s}, {e} + 1)"
            else:
                return f"range({s}, {e})"
        if isinstance(node, BinOp):
            return self.gen_binop(node)
        if isinstance(node, UnaryOp):
            operand = self.gen_expr(node.operand)
            return f"(-{operand})" if node.op == '-' else f"(not {operand})"
        if isinstance(node, Assign):
            val = self.gen_expr(node.value)
            return f"({node.name} := {val})"
        if isinstance(node, IndexAccess):
            target = self.gen_expr(node.target)
            # Range slice: v[1..3]
            if isinstance(node.index, RangeLiteral):
                s = self.gen_expr(node.index.start)
                e = self.gen_expr(node.index.end)
                if node.index.inclusive:
                    return f"_fk_slice({target}, {s}, {e}, inclusive=True)"
                else:
                    return f"_fk_slice({target}, {s}, {e}, inclusive=False)"
            index = self.gen_expr(node.index)
            # Nil-safe access via helper (handles both dicts and lists)
            return f"_fk_index({target}, {index})"
        if isinstance(node, FuncCall):
            return self.gen_func_call(node)
        if isinstance(node, MethodCall):
            return self.gen_method_call(node)
        if isinstance(node, SafeNavCall):
            return self.gen_safe_nav_call(node)
        if isinstance(node, PipeOp):
            return self.gen_pipe(node)
        if isinstance(node, MatchOp):
            left = self.gen_expr(node.left)
            right = self.gen_expr(node.right)
            return f"_fk_match_op({left}, {right})"
        if isinstance(node, InputExpr):
            return self.gen_input(node)
        if isinstance(node, NamedArg):
            return f"{_py_safe(node.name)}={self.gen_expr(node.value)}"
        if isinstance(node, LambdaLiteral):
            return self.gen_lambda(node)
        if isinstance(node, IfExpr):
            cond = self.gen_expr(node.condition)
            then = self.gen_expr(node.then_expr)
            els = self.gen_expr(node.else_expr) if node.else_expr is not None else "None"
            return f"({then} if {cond} else {els})"
        if isinstance(node, TernaryExpr):
            cond = self.gen_expr(node.condition)
            then = self.gen_expr(node.then_expr)
            els  = self.gen_expr(node.else_expr)
            return f"({then} if {cond} else {els})"
        if isinstance(node, AwaitExpr):
            # In Frankie's threading model, await is a no-op at the expression
            # level — the value is returned directly (the async route handler
            # runs in its own thread so blocking calls are fine there).
            return self.gen_expr(node.expr)
        if isinstance(node, TimeoutBlock):
            # timeout(n) do ... end used as expression — wrap in a call that returns value
            secs = self.gen_expr(node.seconds)
            fn_name = self.temp_var("_timeout_fn")
            self.emit(f"def {fn_name}():")
            self.indent()
            self._gen_body_implicit_return(node.body)
            self.dedent()
            return f"_fk_timeout({secs}, {fn_name})"
        if isinstance(node, SpawnBlock):
            # spawn used as expression — runs block, returns None
            fn_name = self.temp_var("_spawn_fn")
            self.emit(f"def {fn_name}():")
            self.indent()
            self.gen_body(node.body)
            self.dedent()
            self.emit(f"_threading.Thread(target={fn_name}, daemon=True).start()")
            return "None"
        raise CodeGenError(f"Unknown expression node: {type(node).__name__}")

    def gen_string(self, node: StringLiteral) -> str:
        """Build a Python string expression from StringLiteral parts."""
        parts = node.parts
        has_interp = any(kind == 'interp' for kind, _ in parts)

        if not has_interp:
            # Plain string — repr() handles newlines, unicode, etc. perfectly
            s = "".join(v for _, v in parts)
            return repr(s)

        # Has interpolation. Check if any literal part contains a newline.
        has_newline = any('\n' in v for kind, v in parts if kind == 'literal')

        # Build the interpolation expressions once (shared by both paths)
        def _interp_expr(val):
            from .lexer import Lexer
            from .parser import Parser
            sub_tokens = Lexer(val.strip()).tokenize()
            sub_ast = Parser(sub_tokens).parse_expr()
            return self.gen_expr(sub_ast)

        # Pre-generate interpolation expressions. If any contains a double
        # quote (e.g. #{h["key"]}), an f-string would need PEP 701
        # (Python 3.12+) — use the concatenation strategy instead so the
        # generated code runs on every supported Python.
        interp_codes = {}
        for idx, (kind, val) in enumerate(parts):
            if kind == 'interp':
                interp_codes[idx] = _interp_expr(val)
        f_string_safe = all('"' not in code and '\\' not in code
                            for code in interp_codes.values())

        if not has_newline and f_string_safe:
            # Single-line f-string: f"..."
            result = 'f"'
            for idx, (kind, val) in enumerate(parts):
                if kind == 'literal':
                    result += val.replace('\\', '\\\\').replace('"', '\\"').replace('{', '{{').replace('}', '}}')
                else:
                    result += '{_fk_to_str(' + interp_codes[idx] + ')}'
            result += '"'
            return result

        # Multiline (heredoc) interpolation, or single-line interpolation whose
        # expressions contain quotes/backslashes (f-string-unsafe pre-3.12).
        # Strategy: build a concatenation of repr() literals and _fk_to_str() calls.
        # This avoids all triple-quote/backslash issues entirely.
        #   repr("line1\n") + _fk_to_str(expr) + repr(" rest\n")
        segments = []
        for idx, (kind, val) in enumerate(parts):
            if kind == 'literal':
                if val:
                    segments.append(repr(val))
            else:
                segments.append(f"_fk_to_str({interp_codes[idx]})")
        if not segments:
            return repr('')
        return " + ".join(segments)

    def gen_binop(self, node: BinOp) -> str:
        left = self.gen_expr(node.left)
        right = self.gen_expr(node.right)
        op_map = {
            '+': '+', '-': '-', '*': '*', '/': '/',
            '//': '//', '%': '%', '**': '**',
            '==': '==', '!=': '!=', '<': '<', '<=': '<=', '>': '>', '>=': '>=',
            'and': 'and', 'or': 'or',
        }
        py_op = op_map.get(node.op, node.op)

        # Hash merge operator: h1 | h2  → {**h1, **h2}
        if node.op == '|':
            return f"_fk_hash_merge({left}, {right})"

        # Vector-aware arithmetic: wrap in helper
        if node.op in ('+', '-', '*', '/', '//', '%', '**'):
            return f"_fk_arith({left!r}, {left}, {right!r}, {right}, {py_op!r})"

        return f"({left} {py_op} {right})"

    def gen_func_call(self, node: FuncCall) -> str:
        # FuncCall with a block — only 'times' is supported this way
        if node.block is not None:
            if node.name == 'times':
                n = self.gen_expr(node.args[0]) if node.args else '0'
                var = node.block.params[0] if node.block.params else '_'
                self.emit(f"for {var} in range({n}):")
                self.indent()
                self.gen_body(node.block.body)
                self.dedent()
                return ""
            # Generic fallback: emit a lambda and call the function.
            # The block lambda goes after positional args but BEFORE named
            # args, so Python keyword-argument ordering stays valid:
            #   parallel_map(urls, workers: 4) do |u| ... end
            #   → parallel_map(urls, <lambda>, workers=4)
            lam = self._block_to_callable(node.block)
            positional = [self.gen_expr(a) for a in node.args
                          if not isinstance(a, NamedArg)]
            named = [f"{_py_safe(a.name)}={self.gen_expr(a.value)}" for a in node.args
                     if isinstance(a, NamedArg)]
            args = positional + [lam] + named
            return f"{_py_safe(node.name)}({', '.join(args)})"

        def gen_arg(a):
            if isinstance(a, NamedArg):
                return f"{_py_safe(a.name)}={self.gen_expr(a.value)}"
            return self.gen_expr(a)
        args = ", ".join(gen_arg(a) for a in node.args)
        # Map built-in Frankie functions to runtime helpers
        stdlib_map = {
            'sum': '_fk_sum',
            'mean': '_fk_mean',
            'min': '_fk_min',
            'max': '_fk_max',
            'abs': '_fk_abs',
            'sqrt': '_fk_sqrt',
            'floor': '_fk_floor',
            'ceil': '_fk_ceil',
            'round': 'fk_round',
            'length': '_fk_length',
            'vec': '_fk_vec',
            'to_int': '_fk_to_int',
            'to_float': '_fk_to_float',
            'to_str': '_fk_to_str',
            'puts': 'print',
            'print': 'print',
            'zip': 'zip',
            'pp': 'pp',
            'times': 'times',
            # v1.16
            'shell':      '_fk_shell',
            'exec_cmd':   '_fk_shell',
            'dotenv':     '_fk_dotenv',
            'smtp_send':  '_fk_smtp_send',
        }
        py_name = stdlib_map.get(node.name, node.name.replace('?', '_q').replace('!', '_bang'))
        if node.name == 'print':
            return f"print(_fk_to_str({args}), end='')"
        if node.name == 'puts':
            return f"print(_fk_to_str({args}))"
        return f"{py_name}({args})"

    def gen_method_call(self, node: MethodCall) -> str:
        recv = self.gen_expr(node.receiver)

        # .times do |i| ... end
        if node.method == 'times':
            return self._gen_times(recv, node)

        # .each do |x| ... end  (or |k,v| for hashes)
        if node.method == 'each':
            return self._gen_each(recv, node)

        # .select do |x| ... end  — keep elements where block is true
        if node.method == 'select':
            return self._gen_block_method(recv, node, '_fk_select')

        # .reject do |x| ... end  — keep elements where block is false
        if node.method == 'reject':
            return self._gen_block_method(recv, node, '_fk_reject')

        # .reduce(init) do |acc, x| ... end
        if node.method == 'reduce' or node.method == 'inject':
            return self._gen_reduce(recv, node)

        # .each_with_object(obj) do |x, obj| ... end
        if node.method == 'each_with_object':
            return self._gen_each_with_object(recv, node)

        # .gsub(pattern) do |m| ... end — block form transforms each match
        if node.method == 'gsub':
            if node.block:
                return self._gen_gsub_with_block(recv, node)
            # No block: plain gsub(pattern, replacement) — fallthrough to generic
            pat = self.gen_expr(node.args[0]) if node.args else '""'
            rep = self.gen_expr(node.args[1]) if len(node.args) > 1 else '""'
            return f"gsub({recv}, {pat}, {rep})"

        # .map_hash do |k, v| [new_k, new_v] end — transform hash → hash
        if node.method == 'map_hash':
            return self._gen_map_hash(recv, node)

        # .any? do |x| ... end
        if node.method == 'any?':
            return self._gen_predicate(recv, node, '_fk_any')

        # .all? do |x| ... end
        if node.method == 'all?':
            return self._gen_predicate(recv, node, '_fk_all')

        # .none? do |x| ... end
        if node.method == 'none?':
            return self._gen_predicate(recv, node, '_fk_none')

        # .count do |x| ... end  OR  .count("substr")  OR  .count (length)
        # OR  .count(table, where) for DB objects (second arg = filter hash)
        if node.method == 'count':
            if node.block:
                return self._gen_predicate(recv, node, '_fk_count_if')
            if node.args:
                args_str = ", ".join(self.gen_expr(a) for a in node.args)
                # Runtime dispatch: DB.count(table[, where]), str.count(sub), list len
                return f"_fk_count_dispatch({recv}, {args_str})"
            return f"_fk_count_dispatch({recv})"

        # .sort_by do |x| ... end
        if node.method == 'sort_by':
            return self._gen_block_method(recv, node, '_fk_sort_by')

        # .min_by do |x| ... end
        if node.method == 'min_by':
            return self._gen_block_method(recv, node, '_fk_min_by')

        # .max_by do |x| ... end
        if node.method == 'max_by':
            return self._gen_block_method(recv, node, '_fk_max_by')

        # .sum do |x| ... end — projected sum (routes to _fk_sum_by, same as sum_by)
        # Must be checked BEFORE the method_map which would swallow the block.
        if node.method == 'sum' and node.block:
            return self._gen_block_method(recv, node, '_fk_sum_by')

        # .sum_by do |x| ... end
        if node.method == 'sum_by':
            return self._gen_block_method(recv, node, '_fk_sum_by')

        # .find / .detect do |x| ... end  — return first matching element
        # Only intercept the block form; .find(table, where) is a DB call → generic fallback
        if node.method in ('find', 'detect') and node.block and not node.args:
            return self._gen_block_method(recv, node, '_fk_find')

        # .flat_map do |x| ... end
        if node.method == 'flat_map':
            return self._gen_block_method(recv, node, '_fk_flat_map')

        # .take(n)
        if node.method == 'take':
            arg = self.gen_expr(node.args[0]) if node.args else '1'
            return f"_fk_take({recv}, {arg})"

        # .drop(n)
        if node.method == 'drop':
            arg = self.gen_expr(node.args[0]) if node.args else '1'
            return f"_fk_drop({recv}, {arg})"

        # .tally
        if node.method == 'tally':
            return f"_fk_tally({recv})"

        # .group_by do |x| ... end  — groups elements by block result → hash of arrays
        if node.method == 'group_by':
            return self._gen_block_method(recv, node, '_fk_group_by')

        # .each_slice(n) do |slice| ... end  — iterate fixed-size chunks
        if node.method == 'each_slice':
            n = self.gen_expr(node.args[0]) if node.args else '2'
            block = node.block
            if block:
                slice_var = block.params[0] if block.params else '_slice'
                self.emit(f"for {slice_var} in _fk_each_slice({recv}, {n}):")
                self.indent()
                self.gen_body(block.body)
                self.dedent()
                return ""
            return f"_fk_each_slice({recv}, {n})"

        # .each_cons(n) do |window| ... end  — iterate sliding windows
        if node.method == 'each_cons':
            n = self.gen_expr(node.args[0]) if node.args else '2'
            block = node.block
            if block:
                win_var = block.params[0] if block.params else '_window'
                self.emit(f"for {win_var} in _fk_each_cons({recv}, {n}):")
                self.indent()
                self.gen_body(block.body)
                self.dedent()
                return ""
            return f"_fk_each_cons({recv}, {n})"

        # Lambda .call(args) — invoke a stored lambda
        if node.method == 'call':
            args = ", ".join(self.gen_expr(a) for a in node.args)
            return f"({recv})({args})"

        # .compact
        if node.method == 'compact':
            return f"_fk_compact({recv})"

        # .chunk(n)
        if node.method == 'chunk':
            arg = self.gen_expr(node.args[0]) if node.args else '2'
            return f"_fk_chunk({recv}, {arg})"

        # .zip(other)
        if node.method == 'zip':
            arg = self.gen_expr(node.args[0]) if node.args else '[]'
            return f"_fk_zip_vecs({recv}, {arg})"

        # v1.18: set operations on vectors (order-preserving, deduped)
        if node.method in ('union', 'intersect', 'difference'):
            arg = self.gen_expr(node.args[0]) if node.args else '[]'
            return f"_fk_{node.method}({recv}, {arg})"

        # .product(other) — cartesian product → [[x,y], ...]
        if node.method == 'product':
            arg = self.gen_expr(node.args[0]) if node.args else '[]'
            return f"_fk_cartesian_product({recv}, {arg})"

        # .flatten  /  .flatten(depth)
        if node.method == 'flatten':
            if node.args:
                depth = self.gen_expr(node.args[0])
                return f"_fk_flatten_deep({recv}, {depth})"
            return f"_fk_flatten_deep({recv}, None)"

        # .map_with_index do |x, i| ... end
        if node.method == 'map_with_index':
            block = node.block
            if block is None:
                return f"list(enumerate({recv}))"
            params = block.params if block.params else ['_x', '_i']
            x_var = params[0] if len(params) > 0 else '_x'
            i_var = params[1] if len(params) > 1 else '_i'
            if len(block.body) == 1:
                body_expr = self.gen_expr(block.body[0])
                return f"[{body_expr} for {i_var}, {x_var} in enumerate({recv})]"
            fn_name = self.temp_var("_mwi_fn")
            self.emit(f"def {fn_name}({x_var}, {i_var}):")
            self.indent()
            for stmt in block.body[:-1]:
                self.gen_stmt(stmt)
            last = block.body[-1]
            if isinstance(last, ReturnStmt):
                self.gen_stmt(last)
            elif isinstance(last, (Assign, CompoundAssign, IndexAssign,
                                   IndexCompoundAssign, OrAssign,
                                   DestructAssign, HashDestructAssign,
                                   ConstAssign, PrintStmt, DebugPrint)):
                self.gen_stmt(last)
                self.emit("return None")
            else:
                self.emit(f"return {self.gen_expr(last)}")
            self.dedent()
            return f"_fk_map_with_index({recv}, {fn_name})"

        # .encode — string → vector of byte ints; vector of byte ints → string
        if node.method == 'encode':
            enc = self.gen_expr(node.args[0]) if node.args else '"utf-8"'
            return f"(_fk_str_encode({recv}, {enc}) if isinstance({recv}, str) else _fk_str_decode({recv}, {enc}))"

        # .decode — vector of byte ints → string (explicit form)
        if node.method == 'decode':
            enc = self.gen_expr(node.args[0]) if node.args else '"utf-8"'
            return f"_fk_str_decode({recv}, {enc})"

        # .each_with_index do |val, idx| ... end
        if node.method == 'each_with_index':
            return self._gen_each_with_index(recv, node)

        # .map do |x| ... end
        if node.method == 'map':
            return self._gen_map(recv, node)

        # .transform_values do |v| ... end  — new hash with transformed values
        if node.method == 'transform_values':
            return self._gen_block_method(recv, node, '_fk_hash_transform_values')

        # .transform_keys do |k| ... end  — new hash with transformed keys
        if node.method == 'transform_keys':
            return self._gen_block_method(recv, node, '_fk_hash_transform_keys')

        # .deep_merge(other)  — recursive hash merge
        if node.method == 'deep_merge':
            arg = self.gen_expr(node.args[0]) if node.args else '{}'
            return f"_fk_hash_deep_merge({recv}, {arg})"

        # .scan(pattern)  — return all capture groups from all matches
        if node.method == 'scan':
            pat = self.gen_expr(node.args[0]) if node.args else '""'
            return f"_fk_str_scan({recv}, {pat})"

        # String / vector methods
        method_map = {
            'upcase':    f"{recv}.upper()",
            'downcase':  f"{recv}.lower()",
            'length':    f"len({recv})",
            'reverse':   f"{recv}[::-1]",
            'strip':     f"{recv}.strip()",
            'lstrip':    f"{recv}.lstrip()",
            'rstrip':    f"{recv}.rstrip()",
            'to_i':      f"int({recv})",
            'to_f':      f"float({recv})",
            'to_s':      f"str({recv})",
            'chars':     f"_fk_chars({recv})",
            'lines':     f"_fk_lines({recv})",
            'chomp':     f"_fk_chomp({recv})",
            'chop':      f"_fk_chop({recv})",
            'ord':       f"_fk_ord({recv})",
            'chr':       f"_fk_chr({recv})",
            'hex':       f"_fk_hex({recv})",
            'oct':       f"_fk_oct({recv})",
            'first':     f"({recv}[0] if {recv} else None)",
            'last':      f"({recv}[-1] if {recv} else None)",
            'empty?':    f"(len({recv}) == 0)",
            'nil?':      f"_fk_is_nil({recv})",
            'sort':      f"sorted({recv})",
            'uniq':      f"list(dict.fromkeys({recv}))",
            'flatten':   f"[_e for _sub in {recv} for _e in (_sub if isinstance(_sub, list) else [_sub])]",
            'sum':       f"_fk_sum({recv})",
            'min':       f"_fk_min({recv})",
            'max':       f"_fk_max({recv})",
            'mean':      f"_fk_mean({recv})",
        }

        if node.method in method_map:
            return method_map[node.method]

        # include? / start_with? / end_with?
        if node.method == 'include?':
            arg = self.gen_expr(node.args[0]) if node.args else '""'
            return f"({arg} in {recv})"
        if node.method == 'start_with?':
            arg = self.gen_expr(node.args[0]) if node.args else '""'
            return f"{recv}.startswith({arg})"
        if node.method == 'end_with?':
            arg = self.gen_expr(node.args[0]) if node.args else '""'
            return f"{recv}.endswith({arg})"
        if node.method == 'center':
            w = self.gen_expr(node.args[0]) if node.args else '0'
            p = self.gen_expr(node.args[1]) if len(node.args) > 1 else '" "'
            return f"_fk_center({recv}, {w}, {p})"
        if node.method == 'ljust':
            w = self.gen_expr(node.args[0]) if node.args else '0'
            p = self.gen_expr(node.args[1]) if len(node.args) > 1 else '" "'
            return f"_fk_ljust({recv}, {w}, {p})"
        if node.method == 'rjust':
            w = self.gen_expr(node.args[0]) if node.args else '0'
            p = self.gen_expr(node.args[1]) if len(node.args) > 1 else '" "'
            return f"_fk_rjust({recv}, {w}, {p})"
        if node.method == 'squeeze':
            arg = self.gen_expr(node.args[0]) if node.args else 'None'
            return f"_fk_squeeze({recv}, {arg})"
        if node.method == 'tr':
            fr = self.gen_expr(node.args[0]) if len(node.args) > 0 else '""'
            to = self.gen_expr(node.args[1]) if len(node.args) > 1 else '""'
            return f"_fk_tr({recv}, {fr}, {to})"
        if node.method == 'delete':
            # If there's a block, it's a web route: app.delete("/path") do |req| ... end
            if node.block:
                fn_name = self.temp_var("_route_fn")
                req_var = node.block.params[0] if node.block.params else '_req'
                self.emit(f"def {fn_name}({req_var}):")
                self.indent()
                self._gen_route_body(node.block.body)
                self.dedent()
                pattern = self.gen_expr(node.args[0]) if node.args else '"/"'
                return f"{recv}.delete({pattern}, {fn_name})"
            if not node.args:
                return f"{recv}.pop()"  # vector pop (no arg)
            if len(node.args) == 2:
                # DB.delete(table, where_hash) — two args means it's a DB call
                arg0 = self.gen_expr(node.args[0])
                arg1 = self.gen_expr(node.args[1])
                return f"{recv}.delete({arg0}, {arg1})"
            arg = self.gen_expr(node.args[0])
            # Single arg: str→delete chars, hash→pop key, vector→remove by value
            return f"(_fk_str_delete({recv}, {arg}) if isinstance({recv}, str) else (_fk_hash_delete({recv}, {arg}) if isinstance({recv}, dict) else (_fk_vec_delete({recv}, {arg}))))"
        if node.method == 'bytes':
            return f"_fk_bytes({recv})"
        if node.method == 'each_char':
            block = node.block
            if block:
                var = block.params[0] if block.params else '_c'
                self.emit(f"for {var} in {recv}:")
                self.indent()
                self.gen_body(block.body)
                self.dedent()
                return ""
            return f"_fk_chars({recv})"
        if node.method == 'each_line':
            block = node.block
            if block:
                var = block.params[0] if block.params else '_line'
                self.emit(f"for {var} in _fk_lines({recv}):")
                self.indent()
                self.gen_body(block.body)
                self.dedent()
                return ""
            return f"_fk_lines({recv})"
        if node.method == 'split':
            arg = self.gen_expr(node.args[0]) if node.args else '" "'
            return f"{recv}.split({arg})"
        if node.method == 'join':
            arg = self.gen_expr(node.args[0]) if node.args else '""'
            return f"{arg}.join([str(_e) for _e in {recv}])"
        if node.method == 'push':
            arg = self.gen_expr(node.args[0]) if node.args else 'None'
            return f"(_fk_list_push({recv}, {arg}))"
        if node.method == 'pop':
            return f"{recv}.pop()"
        if node.method == 'keys':
            return f"list({recv}.keys())"
        if node.method == 'values':
            return f"list({recv}.values())"
        if node.method == 'has_key?':
            arg = self.gen_expr(node.args[0]) if node.args else '""'
            return f"({arg} in {recv})"
        if node.method == 'merge':
            arg = self.gen_expr(node.args[0]) if node.args else '{}'
            return "{" + f"**{recv}, **{arg}" + "}"
        if node.method == 'merge_bang':
            arg = self.gen_expr(node.args[0]) if node.args else '{}'
            return f"(_fk_hash_merge_bang({recv}, {arg}))"
        if node.method in ('size', 'count'):
            return f"len({recv})"
        if node.method == 'dig':
            keys = ", ".join(self.gen_expr(a) for a in node.args)
            return f"_fk_dig({recv}, {keys})"
        if node.method in ('to_a', 'to_vec'):
            # Runtime dispatch: hash → list of [k, v] pairs; range/string/vector → list
            return f"_fk_to_vec({recv})"
        # .step(n) — range stride: (1..10).step(2) → [1, 3, 5, 7, 9]
        if node.method == 'step':
            arg = self.gen_expr(node.args[0]) if node.args else '1'
            return f"_fk_range_step({recv}, {arg})"
        if node.method == 'each_pair':
            block = node.block
            if block is None:
                return f"list({recv}.items())"
            k_var = block.params[0] if len(block.params) > 0 else '_k'
            v_var = block.params[1] if len(block.params) > 1 else '_v'
            self.emit(f"for {k_var}, {v_var} in {recv}.items():")
            self.indent()
            self.gen_body(block.body)
            self.dedent()
            return ""
        if node.method == 'each':
            block = node.block
            if block and len(block.params) == 2:
                k_var, v_var = block.params[0], block.params[1]
                self.emit(f"for {k_var}, {v_var} in {recv}.items():")
                self.indent()
                self.gen_body(block.body)
                self.dedent()
                return ""
            elif block and len(block.params) == 1:
                pair_var = block.params[0]
                self.emit(f"for {pair_var} in {recv}.items():")
                self.indent()
                self.gen_body(block.body)
                self.dedent()
                return ""
            return f"list({recv}.items())"
        if node.method == 'fetch':
            arg = self.gen_expr(node.args[0]) if node.args else '""'
            default = self.gen_expr(node.args[1]) if len(node.args) > 1 else 'None'
            return f"{recv}.get({arg}, {default})"
        if node.method == 'store':
            k = self.gen_expr(node.args[0]) if len(node.args) > 0 else '""'
            v = self.gen_expr(node.args[1]) if len(node.args) > 1 else 'None'
            return f"(_fk_hash_store({recv}, {k}, {v}))"

        # ── Property accessors (no parens) ─────────────────────────────────────
        # DateTime + HTTP response + FrankieRequest attributes
        # Only treat as property when called with no args and no block
        if node.method in ('year','month','day','hour','minute','second',
                           'status','body','headers','content_type',
                           'params','query','form','path','method') and not node.args and not node.block:
            return f"{recv}.{node.method}"

        # .json is a property on FrankieRequest but a method on HTTP responses.
        # With no args and no block, treat it as a property (req.json).
        if node.method == 'json' and not node.args and not node.block:
            return f"{recv}.json"

        # ── Query-string typed helpers ────────────────────────────────────────
        if node.method in ('query_int', 'query_float', 'query_bool'):
            args = [self.gen_expr(a) for a in node.args]
            args_str = ', '.join(args)
            return f"{recv}.{node.method}({args_str})"

        # ── DateTime methods ──────────────────────────────────────────────────
        if node.method == 'add_days':
            arg = self.gen_expr(node.args[0]) if node.args else '1'
            return f"{recv}.add_days({arg})"
        if node.method == 'add_hours':
            arg = self.gen_expr(node.args[0]) if node.args else '1'
            return f"{recv}.add_hours({arg})"
        if node.method == 'add_minutes':
            arg = self.gen_expr(node.args[0]) if node.args else '1'
            return f"{recv}.add_minutes({arg})"
        if node.method == 'diff_days':
            arg = self.gen_expr(node.args[0]) if node.args else 'None'
            return f"{recv}.diff_days({arg})"
        if node.method == 'diff_seconds':
            arg = self.gen_expr(node.args[0]) if node.args else 'None'
            return f"{recv}.diff_seconds({arg})"
        if node.method == 'weekday':
            return f"{recv}.weekday()"
        if node.method == 'weekday_name':
            return f"{recv}.weekday_name()"
        if node.method == 'is_before':
            arg = self.gen_expr(node.args[0]) if node.args else 'None'
            return f"{recv}.is_before({arg})"
        if node.method == 'is_after':
            arg = self.gen_expr(node.args[0]) if node.args else 'None'
            return f"{recv}.is_after({arg})"
        if node.method == 'timestamp':
            return f"{recv}.timestamp()"
        if node.method == 'to_s':
            return f"_fk_to_str({recv})"

        # ── HTTP response methods ─────────────────────────────────────────────
        if node.method == 'json':
            return f"{recv}.json()"
        if node.method == 'ok':
            if not node.args and not node.block:
                return f"{recv}.ok()"

        # ── Database methods ──────────────────────────────────────────────────
        # transaction do ... end  — wraps body in begin/commit/rollback
        if node.method == 'transaction':
            block = node.block
            if block:
                self.emit("try:")
                self.indent()
                self.emit(f"{recv}.begin()")
                self.gen_body(block.body)
                self.emit(f"{recv}.commit()")
                self.dedent()
                self.emit("except Exception as _tx_err:")
                self.indent()
                self.emit(f"{recv}.rollback()")
                self.emit("raise _tx_err")
                self.dedent()
                return ""
            return f"{recv}.begin()"

        # ── Web app route/filter registration ────────────────────────────────
        # app.get("/path") do |req| ... end
        # app.post / put / delete / patch / before / after / not_found
        # v1.18: app.websocket("/ws") do |ws| ... end
        if node.method in ('get', 'post', 'put', 'delete', 'patch',
                           'before', 'after', 'not_found', 'websocket'):
            block = node.block
            if block:
                # Emit a named handler function then pass it as an argument
                fn_name  = self.temp_var("_route_fn")
                req_var  = block.params[0] if block.params else '_req'
                # after-filter receives (req, res)
                if node.method == 'after' and len(block.params) >= 2:
                    req_var = f"{block.params[0]}, {block.params[1]}"
                self.emit(f"def {fn_name}({req_var}):")
                self.indent()
                self._gen_route_body(block.body)
                self.dedent()
                # after/before/not_found take only the handler
                if node.method in ('before', 'after', 'not_found'):
                    return f"{recv}.{node.method}({fn_name})"
                # route methods take (pattern, handler)
                pattern = self.gen_expr(node.args[0]) if node.args else '"/..."'
                return f"{recv}.{node.method}({pattern}, {fn_name})"
            # No block — plain call (e.g. programmatic registration)
            args = ", ".join(self.gen_expr(a) for a in node.args)
            return f"{recv}.{node.method}({args})"

        # ── web app .run(port) ────────────────────────────────────────────────
        if node.method == 'run' and not node.block:
            args = ", ".join(self.gen_expr(a) for a in node.args)
            return f"{recv}.run({args})"

        if node.method == 'replace':
            old = self.gen_expr(node.args[0]) if len(node.args) > 0 else '""'
            new = self.gen_expr(node.args[1]) if len(node.args) > 1 else '""'
            return f"_fk_str_sub({recv}, {old}, {new})"

        if node.method == 'match':
            pat = self.gen_expr(node.args[0]) if node.args else '""'
            return f"match({recv}, {pat})"

        if node.method == 'match_all':
            pat = self.gen_expr(node.args[0]) if node.args else '""'
            return f"match_all({recv}, {pat})"

        if node.method in ('matches?', 'matches'):
            pat = self.gen_expr(node.args[0]) if node.args else '""'
            return f"matches({recv}, {pat})"

        if node.method == 'sub':
            pat = self.gen_expr(node.args[0]) if len(node.args) > 0 else '""'
            rep = self.gen_expr(node.args[1]) if len(node.args) > 1 else '""'
            return f"sub({recv}, {pat}, {rep})"

        if node.method == 'format':
            if node.args:
                arg = self.gen_expr(node.args[0])
                # Runtime dispatch: if arg is a dict → str .format(hash); else → datetime .format(fmt)
                return f"(_fk_str_format({recv}, {arg}) if isinstance({recv}, str) else {recv}.format({arg}))"
            return f'{recv}.format("%Y-%m-%d %H:%M:%S")'

        if node.method == 'zip_with':
            other = self.gen_expr(node.args[0]) if node.args else '[]'
            block = node.block
            if block is None:
                return f"_fk_zip_with({recv}, {other}, lambda a, b: [a, b])"
            params = block.params if block.params else ['_a', '_b']
            a_var = params[0] if len(params) > 0 else '_a'
            b_var = params[1] if len(params) > 1 else '_b'
            fn_name = self.temp_var("_zw_fn")
            self.emit(f"def {fn_name}({a_var}, {b_var}):")
            self.indent()
            self._gen_body_implicit_return(block.body)
            self.dedent()
            return f"_fk_zip_with({recv}, {other}, {fn_name})"

        # Generic fallback — handles all other method calls including
        # DB methods: exec, query, query_one, insert, insert_many,
        # find_all, find, find_one, update, delete, count, tables,
        # columns, last_id, begin, commit, rollback, close
        #
        # v1.17: zero-arg, no-block calls dispatch through _fk_attr_or_method
        # so they work as attribute access too — record fields (p.x),
        # module constants (math.PI) and zero-arg methods (db.tables) all
        # resolve correctly at runtime.
        if not node.args and node.block is None:
            return f"_fk_attr_or_method({recv}, {_py_safe(node.method)!r})"
        args = ", ".join(self.gen_expr(a) for a in node.args)
        return f"{recv}.{_py_safe(node.method)}({args})"

    def gen_safe_nav_call(self, node: SafeNavCall) -> str:
        """Generate nil-safe navigation: x&.method(args) → None if x is None else x.method(args)
        Reuses gen_method_call so all Frankie method aliases (upcase→upper, etc.) work correctly.
        """
        recv_expr = self.gen_expr(node.receiver)
        # Build a synthetic MethodCall routed through the normal method codegen path,
        # but using a temp-var receiver so we don't evaluate the receiver expression twice.
        tmp = self.temp_var("_snav")
        # Emit the temp assignment as a statement first — we need it before the expression.
        # Since gen_expr is called in expression context, we use a Python walrus trick instead:
        # (tmp := recv_expr) is not None evaluated inline.
        # Generate what the inner method call would look like via a dummy node:
        dummy = MethodCall(receiver=node.receiver, method=node.method,
                           args=node.args, block=node.block)
        inner = self.gen_method_call(dummy)
        # Wrap with nil guard. Routed through _fk_is_nil rather than inlining
        # `is None` directly — see _fk_is_nil's docstring: a literal receiver
        # (e.g. "x"&.upcase) would otherwise trigger Python's spurious
        # SyntaxWarning for `is` with a literal.
        return f"(None if _fk_is_nil({recv_expr}) else {inner})"

    def _gen_times(self, recv, node: MethodCall) -> str:
        """Generate a for loop for N.times do |i| ... end"""
        block = node.block
        if block is None:
            return f"_fk_times({recv}, lambda: None)"
        var = block.params[0] if block.params else '_'
        # Can't return expr for a loop — emit statements instead
        self.emit(f"for {var} in range({recv}):")
        self.indent()
        self.gen_body(block.body)
        self.dedent()
        return ""

    def _gen_each(self, recv, node: MethodCall) -> str:
        block = node.block
        if block is None:
            return f"_fk_each({recv})"
        recv_tmp = self.temp_var("_each_recv")
        self.emit(f"{recv_tmp} = {recv}")
        result_tmp = self.temp_var("_each_result")
        # Two params → hash iteration: do |key, val|
        if len(block.params) == 2:
            k_var, v_var = block.params[0], block.params[1]
            self.emit(f"for {k_var}, {v_var} in ({recv_tmp}.items() if isinstance({recv_tmp}, dict) else enumerate({recv_tmp})):")
            self.indent()
            self.gen_body(block.body)
            self.dedent()
        else:
            var = block.params[0] if block.params else '_'
            self.emit(f"for {var} in {recv_tmp}:")
            self.indent()
            self.gen_body(block.body)
            self.dedent()
        # .each's value: the result of `break value` if the loop was broken
        # out of, otherwise the receiver itself (Ruby's `.each` convention).
        # `for...else` only runs the else-branch when the loop was NOT broken,
        # so it's the cleanest way to tell the two cases apart here.
        self.emit("else:")
        self.indent()
        self.emit(f"_fk_break_val = {recv_tmp}")
        self.dedent()
        self.emit(f"{result_tmp} = _fk_break_val")
        return result_tmp

    def _gen_each_with_index(self, recv, node: MethodCall) -> str:
        block = node.block
        if block is None:
            return f"_fk_each_with_index({recv})"
        recv_tmp = self.temp_var("_each_recv")
        self.emit(f"{recv_tmp} = {recv}")
        result_tmp = self.temp_var("_each_result")
        val_var = block.params[0] if len(block.params) > 0 else '_v'
        idx_var = block.params[1] if len(block.params) > 1 else '_i'
        self.emit(f"for {idx_var}, {val_var} in enumerate({recv_tmp}):")
        self.indent()
        self.gen_body(block.body)
        self.dedent()
        self.emit("else:")
        self.indent()
        self.emit(f"_fk_break_val = {recv_tmp}")
        self.dedent()
        self.emit(f"{result_tmp} = _fk_break_val")
        return result_tmp

    def _gen_map(self, recv, node: MethodCall) -> str:
        block = node.block
        if block is None:
            return f"list({recv})"

        # Two block params on a hash: |k, v| — iterate items()
        if block.params and len(block.params) == 2:
            k_var = block.params[0]
            v_var = block.params[1]
            recv_tmp = self.temp_var("_map_recv")
            self.emit(f"{recv_tmp} = {recv}")
            _CTRL_FLOW = (IfStmt, UnlessStmt, WhileStmt, UntilStmt, DoWhileStmt,
                          ForInStmt, BeginRescue, CaseStmt, IndexAssign, IndexCompoundAssign, CompoundAssign, OrAssign, DestructAssign, HashDestructAssign, ConstAssign, PostfixIf)
            if (len(block.body) == 1 and not isinstance(block.body[0], _CTRL_FLOW)
                    and not _is_times_block_call(block.body[0])):
                body_expr = self.gen_expr(block.body[0])
                return (f"[{body_expr} for {k_var}, {v_var} in "
                        f"({recv_tmp}.items() if isinstance({recv_tmp}, dict) else {recv_tmp})]")
            fn_name = self.temp_var("_map_fn")
            self.emit(f"def {fn_name}({k_var}, {v_var}):")
            self.indent()
            for stmt in block.body[:-1]:
                self.gen_stmt(stmt)
            last = block.body[-1]
            if isinstance(last, IfStmt):
                self._gen_if_implicit_return(last)
            elif isinstance(last, UnlessStmt):
                self._gen_unless_implicit_return(last)
            elif isinstance(last, _CTRL_FLOW):
                self.gen_stmt(last)
                self.emit("return None")
            else:
                self.emit(f"return {self.gen_expr(last)}")
            self.dedent()
            return (f"[{fn_name}(*_pair) for _pair in "
                    f"({recv_tmp}.items() if isinstance({recv_tmp}, dict) else {recv_tmp})]")

        var = block.params[0] if block.params else '_'
        _CTRL_FLOW = (IfStmt, UnlessStmt, WhileStmt, UntilStmt, DoWhileStmt,
                      ForInStmt, BeginRescue, CaseStmt, IndexAssign, IndexCompoundAssign, CompoundAssign, OrAssign, DestructAssign, HashDestructAssign, ConstAssign, PostfixIf)
        # map returns a value — use list comprehension for simple single-expr blocks
        if (len(block.body) == 1 and not isinstance(block.body[0], _CTRL_FLOW)
                and not _is_times_block_call(block.body[0])):
            body_expr = self.gen_expr(block.body[0])
            return f"[{body_expr} for {var} in {recv}]"
        # Multi-statement map, or single control-flow node: emit a helper function
        fn_name = self.temp_var("_map_fn")
        self.emit(f"def {fn_name}({var}):")
        self.indent()
        for stmt in block.body[:-1]:
            self.gen_stmt(stmt)
        last = block.body[-1]
        if isinstance(last, IfStmt):
            self._gen_if_implicit_return(last)
        elif isinstance(last, UnlessStmt):
            self._gen_unless_implicit_return(last)
        elif isinstance(last, _CTRL_FLOW):
            self.gen_stmt(last)
            self.emit("return None")
        else:
            self.emit(f"return {self.gen_expr(last)}")
        self.dedent()
        return f"[{fn_name}({var}) for {var} in {recv}]"

    def _block_to_callable(self, block) -> str:
        """Convert a block to a Python callable with the block's EXACT
        parameter list (zero, one or many params). Used for generic
        function-call blocks: test "x" do ... end, parallel_map do |u| ... end.
        """
        _CTRL_FLOW = (IfStmt, UnlessStmt, WhileStmt, UntilStmt, DoWhileStmt,
                      ForInStmt, BeginRescue, CaseStmt, PrintStmt, DebugPrint,
                      ReturnStmt, FuncDef, RaiseStmt, IndexAssign, IndexCompoundAssign, CompoundAssign, OrAssign, DestructAssign, HashDestructAssign, ConstAssign, PostfixIf)
        params_str = ", ".join(_py_safe(p) for p in block.params)
        if (len(block.body) == 1 and not isinstance(block.body[0], _CTRL_FLOW)
                and not _is_times_block_call(block.body[0])):
            return f"lambda {params_str}: {self.gen_expr(block.body[0])}"
        fn_name = self.temp_var("_blk_fn")
        self.emit(f"def {fn_name}({params_str}):")
        self.indent()
        for stmt in block.body[:-1]:
            self.gen_stmt(stmt)
        last = block.body[-1]
        self._touch_line(last)
        if isinstance(last, ReturnStmt):
            self.gen_stmt(last)
        elif isinstance(last, _CTRL_FLOW):
            result_var = self.temp_var("_blk_result")
            self.emit(f"{result_var} = None")
            self._emit_stmt_as_value(last, result_var)
            self.emit(f"return {result_var}")
        else:
            self.emit(f"return {self.gen_expr(last)}")
        self.dedent()
        return fn_name

    def _block_to_lambda(self, block, recv) -> str:
        """Convert a block to a Python lambda string.
        Single-expression, non-control-flow blocks become inline lambdas.
        Everything else becomes a named helper function.
        """
        _CTRL_FLOW = (IfStmt, UnlessStmt, WhileStmt, UntilStmt, DoWhileStmt,
                      ForInStmt, BeginRescue, CaseStmt, PrintStmt, DebugPrint,
                      ReturnStmt, FuncDef, RaiseStmt, IndexAssign, IndexCompoundAssign, CompoundAssign, OrAssign, DestructAssign, HashDestructAssign, ConstAssign, PostfixIf)
        var = block.params[0] if block.params else '_'
        if (len(block.body) == 1 and not isinstance(block.body[0], _CTRL_FLOW)
                and not _is_times_block_call(block.body[0])):
            body_expr = self.gen_expr(block.body[0])
            return f"lambda {var}: {body_expr}"
        # Multi-statement or control-flow: emit a helper function
        fn_name = self.temp_var("_blk_fn")
        self.emit(f"def {fn_name}({var}):")
        self.indent()
        for stmt in block.body[:-1]:
            self.gen_stmt(stmt)
        last = block.body[-1]
        if isinstance(last, ReturnStmt):
            self.gen_stmt(last)
        elif isinstance(last, _CTRL_FLOW):
            # If the last statement is control flow (e.g. if/else used as expression),
            # we need to capture its result via a temp variable.
            result_var = self.temp_var("_blk_result")
            self.emit(f"{result_var} = None")
            # Emit the if/case and assign into result_var
            self._emit_stmt_as_value(last, result_var)
            self.emit(f"return {result_var}")
        else:
            last_expr = self.gen_expr(last)
            self.emit(f"return {last_expr}")
        self.dedent()
        return fn_name

    def _emit_stmt_as_value(self, node, result_var: str):
        """Emit a statement (typically if/case) whose value should be captured in result_var."""
        if isinstance(node, IfStmt):
            cond = self.gen_expr(node.condition)
            self.emit(f"if {cond}:")
            self.indent()
            self._emit_body_as_value(node.then_body, result_var)
            self.dedent()
            for ec, eb in node.elsif_clauses:
                self.emit(f"elif {self.gen_expr(ec)}:")
                self.indent()
                self._emit_body_as_value(eb, result_var)
                self.dedent()
            if node.else_body is not None:
                self.emit("else:")
                self.indent()
                self._emit_body_as_value(node.else_body, result_var)
                self.dedent()
        elif isinstance(node, CaseStmt):
            if node.subject is not None:
                subj = self.gen_expr(node.subject)
                subj_tmp = self.temp_var("_case")
                self.emit(f"{subj_tmp} = {subj}")
            first = True
            for values, body in node.when_clauses:
                if node.subject is not None:
                    cond = " or ".join(self._case_cond(subj_tmp, v) for v in values)
                else:
                    cond = " or ".join(self.gen_expr(v) for v in values)
                kw = "if" if first else "elif"
                self.emit(f"{kw} {cond}:")
                self.indent()
                self._emit_body_as_value(body, result_var)
                self.dedent()
                first = False
            if node.else_body:
                self.emit("else:")
                self.indent()
                self._emit_body_as_value(node.else_body, result_var)
                self.dedent()
        else:
            # Fallback: emit normally (result won't be captured, but won't crash)
            self.gen_stmt(node)

    def _emit_body_as_value(self, body, result_var: str):
        """Emit a body list, assigning the last expression result to result_var."""
        _CTRL_FLOW = (IfStmt, UnlessStmt, WhileStmt, UntilStmt, DoWhileStmt,
                      ForInStmt, BeginRescue, CaseStmt, PrintStmt, DebugPrint,
                      ReturnStmt, FuncDef, RaiseStmt, IndexAssign, IndexCompoundAssign, CompoundAssign, OrAssign, DestructAssign, HashDestructAssign, ConstAssign, PostfixIf)
        if not body:
            return
        for stmt in body[:-1]:
            self.gen_stmt(stmt)
        last = body[-1]
        if isinstance(last, ReturnStmt):
            if last.value:
                self.emit(f"{result_var} = {self.gen_expr(last.value)}")
            return
        if isinstance(last, _CTRL_FLOW):
            self._emit_stmt_as_value(last, result_var)
        else:
            self.emit(f"{result_var} = {self.gen_expr(last)}")

    def _gen_block_method(self, recv, node: MethodCall, helper: str) -> str:
        """Generate: helper(recv, lambda x: body)
        For two-param blocks (|k, v|), unpacks the [key, value] pair."""
        block = node.block
        if block is None:
            return f"{helper}({recv}, lambda x: x)"
        # Two-param block: |k, v| — unpack [key, value] pair
        if block.params and len(block.params) == 2:
            k_var = block.params[0]
            v_var = block.params[1]
            fn_name = self.temp_var("_blk2_fn")
            self.emit(f"def {fn_name}(_pair):")
            self.indent()
            self.emit(f"{k_var} = _pair[0]")
            self.emit(f"{v_var} = _pair[1]")
            for stmt in block.body[:-1]:
                self.gen_stmt(stmt)
            last = block.body[-1]
            if isinstance(last, ReturnStmt):
                self.gen_stmt(last)
            elif isinstance(last, (Assign, CompoundAssign, IndexAssign,
                                   IndexCompoundAssign, OrAssign,
                                   DestructAssign, HashDestructAssign,
                                   ConstAssign, PrintStmt, DebugPrint)):
                self.gen_stmt(last)
                self.emit("return None")
            else:
                self.emit(f"return {self.gen_expr(last)}")
            self.dedent()
            return f"{helper}({recv}, {fn_name})"
        lam = self._block_to_lambda(block, recv)
        return f"{helper}({recv}, {lam})"

    def _gen_predicate(self, recv, node: MethodCall, helper: str) -> str:
        """Generate: helper(recv, lambda x: body)
        For two-param blocks (|k, v|), unpacks the [key, value] pair."""
        block = node.block
        if block is None:
            return f"{helper}({recv})"
        # Two-param block: |k, v| — unpack [key, value] pair
        if block.params and len(block.params) == 2:
            k_var = block.params[0]
            v_var = block.params[1]
            fn_name = self.temp_var("_pred2_fn")
            self.emit(f"def {fn_name}(_pair):")
            self.indent()
            self.emit(f"{k_var} = _pair[0]")
            self.emit(f"{v_var} = _pair[1]")
            for stmt in block.body[:-1]:
                self.gen_stmt(stmt)
            last = block.body[-1]
            if isinstance(last, ReturnStmt):
                self.gen_stmt(last)
            elif isinstance(last, (Assign, CompoundAssign, IndexAssign,
                                   IndexCompoundAssign, OrAssign,
                                   DestructAssign, HashDestructAssign,
                                   ConstAssign, PrintStmt, DebugPrint)):
                self.gen_stmt(last)
                self.emit("return None")
            else:
                self.emit(f"return {self.gen_expr(last)}")
            self.dedent()
            return f"{helper}({recv}, {fn_name})"
        lam = self._block_to_lambda(block, recv)
        return f"{helper}({recv}, {lam})"

    def _gen_reduce(self, recv, node: MethodCall) -> str:
        """Generate reduce/inject with optional initial value and block."""
        block = node.block
        initial = self.gen_expr(node.args[0]) if node.args else 'None'
        if block is None:
            return f"_fk_reduce({recv}, lambda a, b: a + b, {initial})"
        params = block.params if block.params else ['_acc', '_x']
        acc_var = params[0] if len(params) > 0 else '_acc'
        x_var   = params[1] if len(params) > 1 else '_x'
        if len(block.body) == 1:
            body_expr = self.gen_expr(block.body[0])
            lam = f"lambda {acc_var}, {x_var}: {body_expr}"
        else:
            fn_name = self.temp_var("_reduce_fn")
            self.emit(f"def {fn_name}({acc_var}, {x_var}):")
            self.indent()
            for stmt in block.body[:-1]:
                self.gen_stmt(stmt)
            last = self.gen_expr(block.body[-1])
            self.emit(f"return {last}")
            self.dedent()
            lam = fn_name
        return f"_fk_reduce({recv}, {lam}, {initial})"

    def _gen_each_with_object(self, recv, node: MethodCall) -> str:
        """Generate each_with_object(init) do |x, obj| ... end"""
        block = node.block
        init = self.gen_expr(node.args[0]) if node.args else '[]'
        if block is None:
            return f"_fk_each_with_object({recv}, {init}, lambda x, o: None)"
        x_var   = block.params[0] if len(block.params) > 0 else '_x'
        obj_var = block.params[1] if len(block.params) > 1 else '_obj'
        obj_tmp = self.temp_var("_ewo_obj")
        recv_tmp = self.temp_var("_ewo_recv")
        self.emit(f"{obj_tmp} = {init}")
        self.emit(f"{recv_tmp} = {recv}")
        # For dicts, iterate items() so block receives [key, value] pairs
        self.emit(f"for {x_var} in ({recv_tmp}.items() if isinstance({recv_tmp}, dict) else {recv_tmp}):")
        self.indent()
        # Wrap dict items as a list so pair[0]/pair[1] work in Frankie
        self.emit(f"if isinstance({recv_tmp}, dict): {x_var} = list({x_var})")
        # bind obj_var to obj_tmp inside the loop
        self.emit(f"{obj_var} = {obj_tmp}")
        self.gen_body(block.body)
        self.dedent()
        return obj_tmp

    def _gen_gsub_with_block(self, recv, node: MethodCall) -> str:
        """Generate str.gsub(pattern) do |m| ... end — block form."""
        block = node.block
        pat = self.gen_expr(node.args[0]) if node.args else '""'
        m_var = block.params[0] if block.params else '_m'
        if len(block.body) == 1:
            body_expr = self.gen_expr(block.body[0])
            return f"_fk_gsub_with_block({recv}, {pat}, lambda {m_var}: {body_expr})"
        fn_name = self.temp_var("_gsub_fn")
        self.emit(f"def {fn_name}({m_var}):")
        self.indent()
        for stmt in block.body[:-1]:
            self.gen_stmt(stmt)
        last = block.body[-1]
        if isinstance(last, ReturnStmt):
            self.gen_stmt(last)
        else:
            self.emit(f"return {self.gen_expr(last)}")
        self.dedent()
        return f"_fk_gsub_with_block({recv}, {pat}, {fn_name})"

    def _gen_map_hash(self, recv, node: MethodCall) -> str:
        """Generate hash.map_hash do |k, v| [new_k, new_v] end"""
        block = node.block
        if block is None:
            return f"_fk_map_hash({recv}, lambda k, v: [k, v])"
        params = block.params if block.params else ['_k', '_v']
        k_var = params[0] if len(params) > 0 else '_k'
        v_var = params[1] if len(params) > 1 else '_v'
        if len(block.body) == 1:
            body_expr = self.gen_expr(block.body[0])
            return f"_fk_map_hash({recv}, lambda {k_var}, {v_var}: {body_expr})"
        fn_name = self.temp_var("_mh_fn")
        self.emit(f"def {fn_name}({k_var}, {v_var}):")
        self.indent()
        for stmt in block.body[:-1]:
            self.gen_stmt(stmt)
        last = block.body[-1]
        if isinstance(last, ReturnStmt):
            self.gen_stmt(last)
        else:
            self.emit(f"return {self.gen_expr(last)}")
        self.dedent()
        return f"_fk_map_hash({recv}, {fn_name})"

    def gen_break(self, node):
        """break / break value / break :label (v1.22)"""
        label = getattr(node, 'label', None)
        if label is not None:
            self.emit(f"raise _FkLoopBreak({label!r})")
            return
        if node.value is None:
            # Always (re)set _fk_break_val, even to None, so a bare `break`
            # can never leave behind a stale value from an earlier `.each`
            # call sharing this scope (e.g. `x = vec.each do ... break ... end`
            # should give nil, not whatever a previous each-with-break-value
            # happened to leave lying around).
            self.emit("_fk_break_val = None")
            self.emit("break")
        else:
            # Python doesn't support break-with-value natively.
            # Use a sentinel variable pattern: _fk_break_val = expr; break
            val = self.gen_expr(node.value)
            self.emit(f"_fk_break_val = {val}")
            self.emit("break")

    def gen_next(self, node):
        """next / next :label (v1.22)"""
        label = getattr(node, 'label', None)
        if label is not None:
            self.emit(f"raise _FkLoopContinue({label!r})")
        else:
            self.emit("continue")

    def gen_const_assign(self, node):
        """UPPER_CASE = value — warn on reassignment via _fk_const_set"""
        val = self.gen_expr(node.value)
        self.emit(f"{node.name} = _fk_const_set({node.name!r}, {val})")

    def _gen_route_body(self, body):
        """
        Emit a route/filter handler body.
        Unlike gen_body, the last expression statement is wrapped in `return`
        so that response helpers like response(), json_response(), halt() etc.
        are returned to the dispatcher rather than discarded. If the handler's
        last statement is an if/unless/case/begin-rescue, we recurse into each
        branch (via _gen_body_implicit_return) so the branch-trailing response
        call is what gets returned — not just discarded because the tail
        happened to be a conditional rather than a bare expression.
        """
        self._gen_body_implicit_return(body)

    def gen_pipe(self, node: PipeOp) -> str:
        left = self.gen_expr(node.left)
        if isinstance(node.right, Identifier):
            # simple function name
            stdlib_map = {
                'sum': '_fk_sum', 'mean': '_fk_mean', 'min': '_fk_min',
                'max': '_fk_max', 'abs': '_fk_abs', 'sqrt': '_fk_sqrt',
                'floor': '_fk_floor', 'ceil': '_fk_ceil', 'length': '_fk_length',
                'to_str': '_fk_to_str', 'to_int': '_fk_to_int',
                'round': 'fk_round',
                'puts': 'print', 'print': 'print',
            }
            fn = stdlib_map.get(node.right.name, node.right.name)
            if fn == 'print':
                return f"print(_fk_to_str({left}), end='')"
            if fn == 'puts':
                return f"print(_fk_to_str({left}))"
            return f"{fn}({left})"
        if isinstance(node.right, FuncCall):
            args_str = ", ".join(self.gen_expr(a) for a in node.right.args)
            all_args = f"{left}, {args_str}" if args_str else left
            return f"{node.right.name}({all_args})"
        right = self.gen_expr(node.right)
        return f"{right}({left})"

    def gen_input(self, node: InputExpr) -> str:
        if node.prompt:
            prompt = self.gen_expr(node.prompt)
            raw = f"input({prompt})"
        else:
            raw = "input()"
        if node.cast == 'int':
            return f"int({raw})"
        if node.cast == 'float':
            return f"float({raw})"
        return raw

    # Map Frankie type names → Python exception classes (zero-dep, no import needed)
    _RESCUE_TYPE_MAP = {
        'RuntimeError':    'RuntimeError',
        'TypeError':       'TypeError',
        'ValueError':      'ValueError',
        'ZeroDivisionError': 'ZeroDivisionError',
        'IndexError':      'IndexError',
        'KeyError':        'KeyError',
        'IOError':         'IOError',
        'FileNotFoundError': 'FileNotFoundError',
        'OverflowError':   'OverflowError',
        'NameError':       'NameError',
        'AttributeError':  'AttributeError',
        'StopIteration':   'StopIteration',
        'TimeoutError':    'TimeoutError',
        'Exception':       'Exception',
        'Error':           'Exception',   # alias
    }

    def gen_begin_rescue(self, node):
        self.emit("try:")
        self.indent()
        self.gen_body(node.body)
        self.dedent()
        clauses = node.rescue_clauses
        for i, clause in enumerate(clauses):
            if clause.error_type is None:
                exc_class = 'Exception'
            else:
                # v1.17: resolved at runtime so user-defined error types
                # (error TimeoutError) take precedence over builtins
                exc_class = f"_fk_exc({clause.error_type!r})"
            tmp = clause.rescue_var or '_fk_err'
            self.emit(f"except {exc_class} as {tmp}:")
            self.indent()
            if clause.body:
                if clause.rescue_var:
                    self.emit(f"{clause.rescue_var} = str({clause.rescue_var})")
                self.gen_body(clause.body)
            else:
                self.emit("pass")
            self.dedent()
        if node.ensure_body:
            self.emit("finally:")
            self.indent()
            self.gen_body(node.ensure_body)
            self.dedent()

    def gen_raise(self, node):
        # v1.17: typed raise — raise TimeoutError, "msg"
        if getattr(node, 'error_type', None):
            if node.message is not None:
                msg = self.gen_expr(node.message)
                self.emit(f"raise _fk_make_error({node.error_type!r}, _fk_to_str({msg}))")
            else:
                self.emit(f"raise _fk_make_error({node.error_type!r}, {node.error_type!r})")
        elif node.message:
            msg = self.gen_expr(node.message)
            self.emit(f"raise RuntimeError(_fk_to_str({msg}))")
        else:
            self.emit("raise")

    def gen_error_def(self, node: 'ErrorDef'):
        """error TimeoutError  →  TimeoutError = _fk_def_error('TimeoutError')"""
        self.emit(f"{node.name} = _fk_def_error({node.name!r})")

    def gen_enum_def(self, node: 'EnumDef'):
        """enum Status(pending, active)  →  Status = _fk_def_enum('Status', [...])"""
        members = ", ".join(repr(m) for m in node.members)
        self.emit(f"{node.name} = _fk_def_enum({node.name!r}, [{members}])")

    def gen_import(self, node: 'ImportStmt'):
        """import "lib/math" as math  →  math = _fk_import("lib/math")"""
        path = self.gen_expr(node.path)
        alias = node.alias
        if alias is None:
            # Default alias: basename without extension ("lib/math" → math)
            if isinstance(node.path, StringLiteral) and node.path.parts:
                raw = "".join(v for k, v in node.path.parts if k == 'literal')
                alias = raw.replace('\\', '/').rsplit('/', 1)[-1]
                alias = alias[:-3] if alias.endswith('.fk') else alias
            else:
                raise CodeGenError("import: 'as' alias required for non-literal paths")
        self.emit(f"{_py_safe(alias)} = _fk_import({path})")

    def gen_require(self, node):
        path = self.gen_expr(node.path)
        self.emit(f"_fk_require({path})")

    def gen_stitch(self, node):
        name = self.gen_expr(node.name)
        self.emit(f"_fk_stitch({name})")

    def gen_case(self, node):
        if node.subject is not None:
            subj = self.gen_expr(node.subject)
            subj_tmp = self.temp_var("_case")
            self.emit(f"{subj_tmp} = {subj}")
        first = True
        for values, body in node.when_clauses:
            if node.subject is not None:
                cond = " or ".join(self._case_cond(subj_tmp, v) for v in values)
            else:
                # bare case: when condition (truthy)
                cond_parts = [self.gen_expr(v) for v in values]
                cond = " or ".join(cond_parts)
            kw = "if" if first else "elif"
            self.emit(f"{kw} {cond}:")
            self.indent()
            self.gen_body(body)
            self.dedent()
            first = False
        if node.else_body is not None:
            self.emit("else:")
            self.indent()
            self.gen_body(node.else_body)
            self.dedent()

    def gen_destruct_assign(self, node):
        value = self.gen_expr(node.value)
        if node.splat_index >= 0:
            n_before = node.splat_index
            n_after  = len(node.names) - node.splat_index - 1
            names    = ", ".join(node.names)
            self.emit(f"{names} = _fk_unpack_splat({value}, {n_before}, {n_after})")
        else:
            names = ", ".join(node.names)
            self.emit(f"{names} = _fk_unpack({value}, {len(node.names)})")

    def gen_record_def(self, node: RecordDef):
        """Generate a record type — a constructor function + hash-based instances.

        record Point(x, y)  generates:
          def Point(x, y):
              return {"__type__": "Point", "x": x, "y": y}

        Plus a structural equality helper and pretty __repr__ in _fk_to_str (handled by
        the existing hash-printing path — __type__ is displayed as the record name).
        """
        fields = node.fields
        params = ", ".join(fields)
        # Constructor
        self.emit(f"def {node.name}({params}):")
        self.indent()
        pairs = ", ".join(f'"{f}": {f}' for f in fields)
        self.emit(f'return {{"__type__": "{node.name}", {pairs}}}')
        self.dedent()
        self.emit()

    def gen_spawn(self, node: SpawnBlock):
        """spawn do ... end  →  threading.Thread(target=lambda: ...).start()"""
        fn_name = self.temp_var("_spawn_fn")
        self.emit(f"def {fn_name}():")
        self.indent()
        self.gen_body(node.body)
        self.dedent()
        self.emit(f"_threading.Thread(target={fn_name}, daemon=True).start()")

    def gen_timeout(self, node: TimeoutBlock):
        """timeout(n) do ... end  →  _fk_timeout(n, fn)"""
        secs = self.gen_expr(node.seconds)
        fn_name = self.temp_var("_timeout_fn")
        self.emit(f"def {fn_name}():")
        self.indent()
        self._gen_body_implicit_return(node.body)
        self.dedent()
        self.emit(f"_fk_timeout({secs}, {fn_name})")

    def gen_hash_destruct_assign(self, node: HashDestructAssign):
        """{name, age} = user  →  name = user.get('name'); age = user.get('age')"""
        val_tmp = self.temp_var("_hd")
        value = self.gen_expr(node.value)
        self.emit(f"{val_tmp} = {value}")
        for key in node.keys:
            self.emit(f"{key} = ({val_tmp}.get({key!r}) if isinstance({val_tmp}, dict) else None)")

    def gen_lambda(self, node: 'LambdaLiteral') -> str:
        """Generate a Python lambda or named inner function for a Frankie lambda literal.
        Single-expression bodies become Python lambdas.
        Multi-statement bodies emit a named helper function and return its reference.
        """
        param_parts = []
        for i, pname in enumerate(node.params):
            default = node.defaults[i] if i < len(node.defaults) else None
            if default is not None:
                param_parts.append(f"{pname}={self.gen_expr(default)}")
            else:
                param_parts.append(pname)
        params_str = ", ".join(param_parts)

        if len(node.body) == 1 and not isinstance(node.body[0], (
                FuncDef, IfStmt, UnlessStmt, WhileStmt, UntilStmt,
                DoWhileStmt, ForInStmt, BeginRescue, CaseStmt,
                PrintStmt, DebugPrint, ReturnStmt, RaiseStmt, IndexAssign, IndexCompoundAssign, CompoundAssign, OrAssign, DestructAssign, HashDestructAssign, ConstAssign, PostfixIf)):
            # Single-expression body → compact lambda
            body_expr = self.gen_expr(node.body[0])
            return f"(lambda {params_str}: {body_expr})"

        # Multi-statement body → named inner function
        fn_name = self.temp_var("_lambda")
        self.emit(f"def {fn_name}({params_str}):")
        self.indent()
        for stmt in node.body[:-1]:
            self.gen_stmt(stmt)
        last = node.body[-1]
        if isinstance(last, ReturnStmt):
            self.gen_stmt(last)
        elif isinstance(last, (FuncDef, IfStmt, UnlessStmt, WhileStmt, UntilStmt,
                                DoWhileStmt, ForInStmt, BeginRescue, CaseStmt,
                                PrintStmt, DebugPrint, RaiseStmt)):
            self.gen_stmt(last)
        else:
            last_expr = self.gen_expr(last)
            self.emit(f"return {last_expr}")
        self.dedent()
        return fn_name

