"""
Frankie Code Generator — Translates Frankie AST into executable Python source code.
"""

import textwrap
from .ast_nodes import *

# Built-in function names (mapped from Frankie → Python/stdlib)
BUILTINS = {
    'sum', 'mean', 'min', 'max', 'abs', 'sqrt', 'floor', 'ceil',
    'length', 'vec', 'to_int', 'to_float', 'to_str', 'range_vec',
    'print_val', 'puts_val',
}

INDENT = "    "


class CodeGenError(Exception):
    pass


class CodeGen:
    def __init__(self):
        self.output = []
        self.indent_level = 0
        self._temp_counter = 0

    def temp_var(self, prefix='_fk'):
        self._temp_counter += 1
        return f"{prefix}_{self._temp_counter}"

    def emit(self, line=""):
        if line:
            self.output.append(INDENT * self.indent_level + line)
        else:
            self.output.append("")

    def indent(self):
        self.indent_level += 1

    def dedent(self):
        self.indent_level -= 1

    def generate(self, program: Program) -> str:
        self.emit("# ── Generated by the Frankie Compiler v1.0 ──────────────────────────")
        self.emit("import math as _math")
        self.emit("import sys as _sys")
        self.emit("from frankie_stdlib import *")
        self.emit("")
        for node in program.body:
            self.gen_stmt(node)
        return "\n".join(self.output)

    # ─── Statements ──────────────────────────────────────────────────────────

    def gen_stmt(self, node: Node):
        if isinstance(node, FuncDef):
            self.gen_func_def(node)
        elif isinstance(node, IfStmt):
            self.gen_if(node)
        elif isinstance(node, UnlessStmt):
            self.gen_unless(node)
        elif isinstance(node, WhileStmt):
            self.gen_while(node)
        elif isinstance(node, UntilStmt):
            self.gen_until(node)
        elif isinstance(node, DoWhileStmt):
            self.gen_do_while(node)
        elif isinstance(node, ForInStmt):
            self.gen_for_in(node)
        elif isinstance(node, ReturnStmt):
            self.gen_return(node)
        elif isinstance(node, PrintStmt):
            self.gen_print(node)
        elif isinstance(node, DebugPrint):
            val = self.gen_expr(node.value)
            self.emit(f"_fk_debug({val})")
        elif isinstance(node, PostfixIf):
            self.gen_postfix_if(node)
        elif isinstance(node, Assign):
            self.gen_assign(node)
        elif isinstance(node, IndexAssign):
            target = self.gen_expr(node.target)
            index = self.gen_expr(node.index)
            value = self.gen_expr(node.value)
            self.emit(f"{target}[{index}] = {value}")
        elif isinstance(node, MethodCall):
            # Statement-level method call (e.g. loop side effects)
            expr = self.gen_method_call(node)
            if expr:
                self.emit(expr)
        elif isinstance(node, PipeOp):
            expr = self.gen_pipe(node)
            self.emit(expr)
        elif isinstance(node, BeginRescue):
            self.gen_begin_rescue(node)
        elif isinstance(node, RaiseStmt):
            self.gen_raise(node)
        elif isinstance(node, RequireStmt):
            self.gen_require(node)
        else:
            # Expression used as statement
            expr = self.gen_expr(node)
            self.emit(expr)

    def gen_body(self, body):
        if not body:
            self.emit("pass")
            return
        for stmt in body:
            self.gen_stmt(stmt)

    # ─── Functions ───────────────────────────────────────────────────────────

    def gen_func_def(self, node: FuncDef):
        params = ", ".join(node.params)
        self.emit(f"def {node.name}({params}):")
        self.indent()
        self.gen_body(node.body)
        self.dedent()
        self.emit()

    # ─── Control Flow ────────────────────────────────────────────────────────

    def gen_if(self, node: IfStmt):
        cond = self.gen_expr(node.condition)
        self.emit(f"if {cond}:")
        self.indent()
        self.gen_body(node.then_body)
        self.dedent()
        for ec, eb in node.elsif_clauses:
            ec_expr = self.gen_expr(ec)
            self.emit(f"elif {ec_expr}:")
            self.indent()
            self.gen_body(eb)
            self.dedent()
        if node.else_body is not None:
            self.emit("else:")
            self.indent()
            self.gen_body(node.else_body)
            self.dedent()

    def gen_unless(self, node: UnlessStmt):
        cond = self.gen_expr(node.condition)
        self.emit(f"if not ({cond}):")
        self.indent()
        self.gen_body(node.then_body)
        self.dedent()
        if node.else_body:
            self.emit("else:")
            self.indent()
            self.gen_body(node.else_body)
            self.dedent()

    def gen_while(self, node: WhileStmt):
        cond = self.gen_expr(node.condition)
        self.emit(f"while {cond}:")
        self.indent()
        self.gen_body(node.body)
        self.dedent()

    def gen_until(self, node: UntilStmt):
        cond = self.gen_expr(node.condition)
        self.emit(f"while not ({cond}):")
        self.indent()
        self.gen_body(node.body)
        self.dedent()

    def gen_do_while(self, node: DoWhileStmt):
        self.emit("while True:")
        self.indent()
        self.gen_body(node.body)
        cond = self.gen_expr(node.condition)
        self.emit(f"if not ({cond}): break")
        self.dedent()

    def gen_for_in(self, node: ForInStmt):
        iterable = self.gen_expr(node.iterable)
        self.emit(f"for {node.var} in {iterable}:")
        self.indent()
        self.gen_body(node.body)
        self.dedent()

    def gen_return(self, node: ReturnStmt):
        if node.value is None:
            self.emit("return")
        else:
            val = self.gen_expr(node.value)
            self.emit(f"return {val}")

    def gen_print(self, node: PrintStmt):
        val = self.gen_expr(node.value)
        if node.newline:
            self.emit(f"print(_fk_to_str({val}))")
        else:
            self.emit(f"print(_fk_to_str({val}), end='')")

    def gen_postfix_if(self, node: PostfixIf):
        cond = self.gen_expr(node.condition)
        if node.negated:
            self.emit(f"if not ({cond}):")
        else:
            self.emit(f"if {cond}:")
        self.indent()
        self.gen_stmt(node.stmt)
        self.dedent()

    def gen_assign(self, node: Assign):
        val = self.gen_expr(node.value)
        self.emit(f"{node.name} = {val}")

    # ─── Expressions ─────────────────────────────────────────────────────────

    def gen_expr(self, node: Node) -> str:
        if isinstance(node, IntLiteral):
            return str(node.value)
        if isinstance(node, FloatLiteral):
            return repr(node.value)
        if isinstance(node, BoolLiteral):
            return "True" if node.value else "False"
        if isinstance(node, NilLiteral):
            return "None"
        if isinstance(node, StringLiteral):
            return self.gen_string(node)
        if isinstance(node, Identifier):
            return node.name
        if isinstance(node, VectorLiteral):
            elems = ", ".join(self.gen_expr(e) for e in node.elements)
            return f"[{elems}]"
        if isinstance(node, HashLiteral):
            pairs = ", ".join(
                f"{self.gen_expr(k)}: {self.gen_expr(v)}"
                for k, v in node.pairs
            )
            return "{" + pairs + "}"
        if isinstance(node, RangeLiteral):
            s = self.gen_expr(node.start)
            e = self.gen_expr(node.end)
            if node.inclusive:
                return f"range({s}, {e} + 1)"
            else:
                return f"range({s}, {e})"
        if isinstance(node, BinOp):
            return self.gen_binop(node)
        if isinstance(node, UnaryOp):
            operand = self.gen_expr(node.operand)
            return f"(-{operand})" if node.op == '-' else f"(not {operand})"
        if isinstance(node, Assign):
            val = self.gen_expr(node.value)
            return f"({node.name} := {val})"
        if isinstance(node, IndexAccess):
            target = self.gen_expr(node.target)
            # Range slice: v[1..3]
            if isinstance(node.index, RangeLiteral):
                s = self.gen_expr(node.index.start)
                e = self.gen_expr(node.index.end)
                if node.index.inclusive:
                    return f"_fk_slice({target}, {s}, {e}, inclusive=True)"
                else:
                    return f"_fk_slice({target}, {s}, {e}, inclusive=False)"
            index = self.gen_expr(node.index)
            # Nil-safe access via helper (handles both dicts and lists)
            return f"_fk_index({target}, {index})"
        if isinstance(node, FuncCall):
            return self.gen_func_call(node)
        if isinstance(node, MethodCall):
            return self.gen_method_call(node)
        if isinstance(node, PipeOp):
            return self.gen_pipe(node)
        if isinstance(node, MatchOp):
            left = self.gen_expr(node.left)
            right = self.gen_expr(node.right)
            return f"_fk_match_op({left}, {right})"
        if isinstance(node, InputExpr):
            return self.gen_input(node)
        if isinstance(node, NamedArg):
            return f"{node.name}={self.gen_expr(node.value)}"
        raise CodeGenError(f"Unknown expression node: {type(node).__name__}")

    def gen_string(self, node: StringLiteral) -> str:
        """Build an f-string or plain string from parts."""
        parts = node.parts
        has_interp = any(kind == 'interp' for kind, _ in parts)
        if not has_interp:
            # Plain string
            s = "".join(v for _, v in parts)
            return repr(s)
        # f-string
        result = 'f"'
        for kind, val in parts:
            if kind == 'literal':
                result += val.replace('\\', '\\\\').replace('"', '\\"').replace('{', '{{').replace('}', '}}')
            else:
                # interp expression — parse and gen
                from .lexer import Lexer
                from .parser import Parser
                sub_tokens = Lexer(val.strip()).tokenize()
                sub_ast = Parser(sub_tokens).parse_expr()
                result += '{_fk_to_str(' + self.gen_expr(sub_ast) + ')}'
        result += '"'
        return result

    def gen_binop(self, node: BinOp) -> str:
        left = self.gen_expr(node.left)
        right = self.gen_expr(node.right)
        op_map = {
            '+': '+', '-': '-', '*': '*', '/': '/',
            '//': '//', '%': '%', '**': '**',
            '==': '==', '!=': '!=', '<': '<', '<=': '<=', '>': '>', '>=': '>=',
            'and': 'and', 'or': 'or',
        }
        py_op = op_map.get(node.op, node.op)

        # Vector-aware arithmetic: wrap in helper
        if node.op in ('+', '-', '*', '/', '//', '%', '**'):
            return f"_fk_arith({left!r}, {left}, {right!r}, {right}, {py_op!r})"

        return f"({left} {py_op} {right})"

    def gen_func_call(self, node: FuncCall) -> str:
        def gen_arg(a):
            if isinstance(a, NamedArg):
                return f"{a.name}={self.gen_expr(a.value)}"
            return self.gen_expr(a)
        args = ", ".join(gen_arg(a) for a in node.args)
        # Map built-in Frankie functions to runtime helpers
        stdlib_map = {
            'sum': '_fk_sum',
            'mean': '_fk_mean',
            'min': '_fk_min',
            'max': '_fk_max',
            'abs': '_fk_abs',
            'sqrt': '_fk_sqrt',
            'floor': '_fk_floor',
            'ceil': '_fk_ceil',
            'length': '_fk_length',
            'vec': '_fk_vec',
            'to_int': '_fk_to_int',
            'to_float': '_fk_to_float',
            'to_str': '_fk_to_str',
            'puts': 'print',
            'print': 'print',
        }
        py_name = stdlib_map.get(node.name, node.name)
        if node.name == 'print':
            return f"print(_fk_to_str({args}), end='')"
        if node.name == 'puts':
            return f"print(_fk_to_str({args}))"
        return f"{py_name}({args})"

    def gen_method_call(self, node: MethodCall) -> str:
        recv = self.gen_expr(node.receiver)

        # .times do |i| ... end
        if node.method == 'times':
            return self._gen_times(recv, node)

        # .each do |x| ... end
        if node.method == 'each':
            return self._gen_each(recv, node)

        # .each_with_index do |val, idx| ... end
        if node.method == 'each_with_index':
            return self._gen_each_with_index(recv, node)

        # .map do |x| ... end
        if node.method == 'map':
            return self._gen_map(recv, node)

        # String / vector methods
        method_map = {
            'upcase':    f"{recv}.upper()",
            'downcase':  f"{recv}.lower()",
            'length':    f"len({recv})",
            'reverse':   f"{recv}[::-1]",
            'strip':     f"{recv}.strip()",
            'to_i':      f"int({recv})",
            'to_f':      f"float({recv})",
            'to_s':      f"str({recv})",
            'first':     f"({recv}[0] if {recv} else None)",
            'last':      f"({recv}[-1] if {recv} else None)",
            'empty?':    f"(len({recv}) == 0)",
            'nil?':      f"({recv} is None)",
            'sort':      f"sorted({recv})",
            'uniq':      f"list(dict.fromkeys({recv}))",
            'flatten':   f"[_e for _sub in {recv} for _e in (_sub if isinstance(_sub, list) else [_sub])]",
            'sum':       f"_fk_sum({recv})",
            'min':       f"_fk_min({recv})",
            'max':       f"_fk_max({recv})",
            'mean':      f"_fk_mean({recv})",
        }

        if node.method in method_map:
            return method_map[node.method]

        # include? / start_with? / end_with?
        if node.method == 'include?':
            arg = self.gen_expr(node.args[0]) if node.args else '""'
            return f"({arg} in {recv})"
        if node.method == 'start_with?':
            arg = self.gen_expr(node.args[0]) if node.args else '""'
            return f"{recv}.startswith({arg})"
        if node.method == 'end_with?':
            arg = self.gen_expr(node.args[0]) if node.args else '""'
            return f"{recv}.endswith({arg})"
        if node.method == 'split':
            arg = self.gen_expr(node.args[0]) if node.args else '" "'
            return f"{recv}.split({arg})"
        if node.method == 'join':
            arg = self.gen_expr(node.args[0]) if node.args else '""'
            return f"{arg}.join([str(_e) for _e in {recv}])"
        if node.method == 'push':
            arg = self.gen_expr(node.args[0]) if node.args else 'None'
            return f"(_fk_list_push({recv}, {arg}))"
        if node.method == 'pop':
            return f"{recv}.pop()"
        if node.method == 'keys':
            return f"list({recv}.keys())"
        if node.method == 'values':
            return f"list({recv}.values())"
        if node.method == 'has_key?':
            arg = self.gen_expr(node.args[0]) if node.args else '""'
            return f"({arg} in {recv})"
        if node.method == 'delete':
            arg = self.gen_expr(node.args[0]) if node.args else '""'
            return f"{recv}.pop({arg}, None)"
        if node.method == 'merge':
            arg = self.gen_expr(node.args[0]) if node.args else '{}'
            return "{" + f"**{recv}, **{arg}" + "}"
        if node.method == 'merge_bang':
            arg = self.gen_expr(node.args[0]) if node.args else '{}'
            return f"(_fk_hash_merge_bang({recv}, {arg}))"
        if node.method in ('size', 'count'):
            return f"len({recv})"
        if node.method == 'to_a':
            return f"list({recv}.items())"
        if node.method == 'each_pair':
            block = node.block
            if block is None:
                return f"list({recv}.items())"
            k_var = block.params[0] if len(block.params) > 0 else '_k'
            v_var = block.params[1] if len(block.params) > 1 else '_v'
            self.emit(f"for {k_var}, {v_var} in {recv}.items():")
            self.indent()
            self.gen_body(block.body)
            self.dedent()
            return ""
        if node.method == 'each':
            block = node.block
            if block and len(block.params) == 2:
                k_var, v_var = block.params[0], block.params[1]
                self.emit(f"for {k_var}, {v_var} in {recv}.items():")
                self.indent()
                self.gen_body(block.body)
                self.dedent()
                return ""
            elif block and len(block.params) == 1:
                pair_var = block.params[0]
                self.emit(f"for {pair_var} in {recv}.items():")
                self.indent()
                self.gen_body(block.body)
                self.dedent()
                return ""
            return f"list({recv}.items())"
        if node.method == 'fetch':
            arg = self.gen_expr(node.args[0]) if node.args else '""'
            default = self.gen_expr(node.args[1]) if len(node.args) > 1 else 'None'
            return f"{recv}.get({arg}, {default})"
        if node.method == 'store':
            k = self.gen_expr(node.args[0]) if len(node.args) > 0 else '""'
            v = self.gen_expr(node.args[1]) if len(node.args) > 1 else 'None'
            return f"(_fk_hash_store({recv}, {k}, {v}))"

        # Generic fallback
        args = ", ".join(self.gen_expr(a) for a in node.args)
        return f"{recv}.{node.method}({args})"

    def _gen_times(self, recv, node: MethodCall) -> str:
        """Generate a for loop for N.times do |i| ... end"""
        block = node.block
        if block is None:
            return f"_fk_times({recv}, lambda: None)"
        var = block.params[0] if block.params else '_'
        # Can't return expr for a loop — emit statements instead
        self.emit(f"for {var} in range({recv}):")
        self.indent()
        self.gen_body(block.body)
        self.dedent()
        return ""

    def _gen_each(self, recv, node: MethodCall) -> str:
        block = node.block
        if block is None:
            return f"_fk_each({recv})"
        # Two params → hash iteration: do |key, val|
        if len(block.params) == 2:
            k_var, v_var = block.params[0], block.params[1]
            self.emit(f"for {k_var}, {v_var} in ({recv}.items() if isinstance({recv}, dict) else enumerate({recv})):")
            self.indent()
            self.gen_body(block.body)
            self.dedent()
            return ""
        var = block.params[0] if block.params else '_'
        self.emit(f"for {var} in {recv}:")
        self.indent()
        self.gen_body(block.body)
        self.dedent()
        return ""

    def _gen_each_with_index(self, recv, node: MethodCall) -> str:
        block = node.block
        if block is None:
            return f"_fk_each_with_index({recv})"
        val_var = block.params[0] if len(block.params) > 0 else '_v'
        idx_var = block.params[1] if len(block.params) > 1 else '_i'
        self.emit(f"for {idx_var}, {val_var} in enumerate({recv}):")
        self.indent()
        self.gen_body(block.body)
        self.dedent()
        return ""

    def _gen_map(self, recv, node: MethodCall) -> str:
        block = node.block
        if block is None:
            return f"list({recv})"
        var = block.params[0] if block.params else '_'
        # map returns a value — use list comprehension
        if len(block.body) == 1:
            body_expr = self.gen_expr(block.body[0])
            return f"[{body_expr} for {var} in {recv}]"
        # Multi-statement map: use lambda with walrus / helper
        # For simplicity, emit as a separate function
        fn_name = self.temp_var("_map_fn")
        self.emit(f"def {fn_name}({var}):")
        self.indent()
        for stmt in block.body[:-1]:
            self.gen_stmt(stmt)
        last = self.gen_expr(block.body[-1])
        self.emit(f"return {last}")
        self.dedent()
        return f"[{fn_name}({var}) for {var} in {recv}]"

    def gen_pipe(self, node: PipeOp) -> str:
        left = self.gen_expr(node.left)
        if isinstance(node.right, Identifier):
            # simple function name
            stdlib_map = {
                'sum': '_fk_sum', 'mean': '_fk_mean', 'min': '_fk_min',
                'max': '_fk_max', 'abs': '_fk_abs', 'sqrt': '_fk_sqrt',
                'floor': '_fk_floor', 'ceil': '_fk_ceil', 'length': '_fk_length',
                'to_str': '_fk_to_str', 'to_int': '_fk_to_int',
                'puts': 'print', 'print': 'print',
            }
            fn = stdlib_map.get(node.right.name, node.right.name)
            if fn == 'print':
                return f"print(_fk_to_str({left}), end='')"
            if fn == 'puts':
                return f"print(_fk_to_str({left}))"
            return f"{fn}({left})"
        if isinstance(node.right, FuncCall):
            args_str = ", ".join(self.gen_expr(a) for a in node.right.args)
            all_args = f"{left}, {args_str}" if args_str else left
            return f"{node.right.name}({all_args})"
        right = self.gen_expr(node.right)
        return f"{right}({left})"

    def gen_input(self, node: InputExpr) -> str:
        if node.prompt:
            prompt = self.gen_expr(node.prompt)
            raw = f"input({prompt})"
        else:
            raw = "input()"
        if node.cast == 'int':
            return f"int({raw})"
        if node.cast == 'float':
            return f"float({raw})"
        return raw

    def gen_begin_rescue(self, node):
        self.emit("try:")
        self.indent()
        self.gen_body(node.body)
        self.dedent()
        self.emit(f"except Exception as {node.rescue_var or '_fk_err'}:")
        self.indent()
        if node.rescue_body:
            # Bind error message to rescue var if given
            if node.rescue_var:
                self.emit(f"{node.rescue_var} = str({node.rescue_var})")
            self.gen_body(node.rescue_body)
        else:
            self.emit("pass")
        self.dedent()
        if node.ensure_body:
            self.emit("finally:")
            self.indent()
            self.gen_body(node.ensure_body)
            self.dedent()

    def gen_raise(self, node):
        if node.message:
            msg = self.gen_expr(node.message)
            self.emit(f"raise RuntimeError(_fk_to_str({msg}))")
        else:
            self.emit("raise")

    def gen_require(self, node):
        path = self.gen_expr(node.path)
        self.emit(f"_fk_require({path})")
