"""
Frankie Code Generator — Translates Frankie AST into executable Python source code.
"""

import textwrap
from .ast_nodes import *

# Built-in function names (mapped from Frankie → Python/stdlib)
BUILTINS = {
    'sum', 'mean', 'min', 'max', 'abs', 'sqrt', 'floor', 'ceil',
    'length', 'vec', 'to_int', 'to_float', 'to_str', 'range_vec',
    'print_val', 'puts_val',
}

INDENT = "    "


class CodeGenError(Exception):
    pass


class CodeGen:
    def __init__(self):
        self.output = []
        self.indent_level = 0
        self._temp_counter = 0

    def temp_var(self, prefix='_fk'):
        self._temp_counter += 1
        return f"{prefix}_{self._temp_counter}"

    def emit(self, line=""):
        if line:
            self.output.append(INDENT * self.indent_level + line)
        else:
            self.output.append("")

    def indent(self):
        self.indent_level += 1

    def dedent(self):
        self.indent_level -= 1

    def generate(self, program: Program, repl_mode: bool = False) -> str:
        if not repl_mode:
            self.emit("# ── Generated by the Frankie Compiler v1.6 ──────────────────────────")
            self.emit("import math as _math")
            self.emit("import sys as _sys")
            self.emit("from frankie_stdlib import *")
            self.emit("")
        for node in program.body:
            self.gen_stmt(node)
        return "\n".join(self.output)

    # ─── Statements ──────────────────────────────────────────────────────────

    def gen_stmt(self, node: Node):
        if isinstance(node, FuncDef):
            self.gen_func_def(node)
        elif isinstance(node, IfStmt):
            self.gen_if(node)
        elif isinstance(node, UnlessStmt):
            self.gen_unless(node)
        elif isinstance(node, WhileStmt):
            self.gen_while(node)
        elif isinstance(node, UntilStmt):
            self.gen_until(node)
        elif isinstance(node, DoWhileStmt):
            self.gen_do_while(node)
        elif isinstance(node, ForInStmt):
            self.gen_for_in(node)
        elif isinstance(node, ReturnStmt):
            self.gen_return(node)
        elif isinstance(node, PrintStmt):
            self.gen_print(node)
        elif isinstance(node, DebugPrint):
            val = self.gen_expr(node.value)
            self.emit(f"_fk_debug({val})")
        elif isinstance(node, PostfixIf):
            self.gen_postfix_if(node)
        elif isinstance(node, Assign):
            self.gen_assign(node)
        elif isinstance(node, CompoundAssign):
            self.gen_compound_assign(node)
        elif isinstance(node, IndexCompoundAssign):
            self.gen_index_compound_assign(node)
        elif isinstance(node, IndexAssign):
            target = self.gen_expr(node.target)
            index = self.gen_expr(node.index)
            value = self.gen_expr(node.value)
            self.emit(f"{target}[{index}] = {value}")
        elif isinstance(node, MethodCall):
            # Statement-level method call (e.g. loop side effects)
            expr = self.gen_method_call(node)
            if expr:
                self.emit(expr)
        elif isinstance(node, PipeOp):
            expr = self.gen_pipe(node)
            self.emit(expr)
        elif isinstance(node, BeginRescue):
            self.gen_begin_rescue(node)
        elif isinstance(node, RaiseStmt):
            self.gen_raise(node)
        elif isinstance(node, RequireStmt):
            self.gen_require(node)
        elif isinstance(node, CaseStmt):
            self.gen_case(node)
        elif isinstance(node, DestructAssign):
            self.gen_destruct_assign(node)
        elif isinstance(node, NextStmt):
            self.emit("continue")
        elif isinstance(node, BreakStmt):
            self.gen_break(node)
        elif isinstance(node, ConstAssign):
            self.gen_const_assign(node)
        else:
            # Expression used as statement
            expr = self.gen_expr(node)
            self.emit(expr)

    def gen_body(self, body):
        if not body:
            self.emit("pass")
            return
        for stmt in body:
            self.gen_stmt(stmt)

    # ─── Functions ───────────────────────────────────────────────────────────

    def gen_func_def(self, node: FuncDef):
        param_parts = []
        for i, pname in enumerate(node.params):
            default = node.defaults[i] if i < len(node.defaults) else None
            if default is not None:
                param_parts.append(f"{pname}={self.gen_expr(default)}")
            else:
                param_parts.append(pname)
        params = ", ".join(param_parts)
        self.emit(f"def {node.name}({params}):")
        self.indent()
        self.gen_body(node.body)
        self.dedent()
        self.emit()

    # ─── Control Flow ────────────────────────────────────────────────────────

    def gen_if(self, node: IfStmt):
        cond = self.gen_expr(node.condition)
        self.emit(f"if {cond}:")
        self.indent()
        self.gen_body(node.then_body)
        self.dedent()
        for ec, eb in node.elsif_clauses:
            ec_expr = self.gen_expr(ec)
            self.emit(f"elif {ec_expr}:")
            self.indent()
            self.gen_body(eb)
            self.dedent()
        if node.else_body is not None:
            self.emit("else:")
            self.indent()
            self.gen_body(node.else_body)
            self.dedent()

    def gen_unless(self, node: UnlessStmt):
        cond = self.gen_expr(node.condition)
        self.emit(f"if not ({cond}):")
        self.indent()
        self.gen_body(node.then_body)
        self.dedent()
        if node.else_body:
            self.emit("else:")
            self.indent()
            self.gen_body(node.else_body)
            self.dedent()

    def gen_while(self, node: WhileStmt):
        cond = self.gen_expr(node.condition)
        self.emit(f"while {cond}:")
        self.indent()
        self.gen_body(node.body)
        self.dedent()

    def gen_until(self, node: UntilStmt):
        cond = self.gen_expr(node.condition)
        self.emit(f"while not ({cond}):")
        self.indent()
        self.gen_body(node.body)
        self.dedent()

    def gen_do_while(self, node: DoWhileStmt):
        self.emit("while True:")
        self.indent()
        self.gen_body(node.body)
        cond = self.gen_expr(node.condition)
        self.emit(f"if not ({cond}): break")
        self.dedent()

    def gen_for_in(self, node: ForInStmt):
        iterable = self.gen_expr(node.iterable)
        self.emit(f"for {node.var} in {iterable}:")
        self.indent()
        self.gen_body(node.body)
        self.dedent()

    def gen_return(self, node: ReturnStmt):
        if node.value is None:
            self.emit("return")
        else:
            val = self.gen_expr(node.value)
            self.emit(f"return {val}")

    def gen_print(self, node: PrintStmt):
        val = self.gen_expr(node.value)
        if node.newline:
            self.emit(f"print(_fk_to_str({val}))")
        else:
            self.emit(f"print(_fk_to_str({val}), end='')")

    def gen_postfix_if(self, node: PostfixIf):
        cond = self.gen_expr(node.condition)
        if node.negated:
            self.emit(f"if not ({cond}):")
        else:
            self.emit(f"if {cond}:")
        self.indent()
        self.gen_stmt(node.stmt)
        self.dedent()

    def gen_assign(self, node: Assign):
        val = self.gen_expr(node.value)
        self.emit(f"{node.name} = {val}")

    def gen_compound_assign(self, node):
        val = self.gen_expr(node.value)
        # Expand to full expression using _fk_arith for type-safe arithmetic
        self.emit(f"{node.name} = _fk_arith(repr({node.name}), {node.name}, repr({val}), {val}, '{node.op}')")

    def gen_index_compound_assign(self, node):
        target = self.gen_expr(node.target)
        idx = self.gen_expr(node.index)
        val = self.gen_expr(node.value)
        self.emit(f"{target}[_fk_index_key({idx})] = _fk_arith(repr({target}[_fk_index_key({idx})]), {target}[_fk_index_key({idx})], repr({val}), {val}, '{node.op}')")

    # ─── Expressions ─────────────────────────────────────────────────────────

    def gen_expr(self, node: Node) -> str:
        if isinstance(node, IntLiteral):
            return str(node.value)
        if isinstance(node, FloatLiteral):
            return repr(node.value)
        if isinstance(node, BoolLiteral):
            return "True" if node.value else "False"
        if isinstance(node, NilLiteral):
            return "None"
        if isinstance(node, StringLiteral):
            return self.gen_string(node)
        if isinstance(node, Identifier):
            return node.name
        if isinstance(node, VectorLiteral):
            elems = ", ".join(self.gen_expr(e) for e in node.elements)
            return f"[{elems}]"
        if isinstance(node, HashLiteral):
            pairs = ", ".join(
                f"{self.gen_expr(k)}: {self.gen_expr(v)}"
                for k, v in node.pairs
            )
            return "{" + pairs + "}"
        if isinstance(node, RangeLiteral):
            s = self.gen_expr(node.start)
            e = self.gen_expr(node.end)
            if node.inclusive:
                return f"range({s}, {e} + 1)"
            else:
                return f"range({s}, {e})"
        if isinstance(node, BinOp):
            return self.gen_binop(node)
        if isinstance(node, UnaryOp):
            operand = self.gen_expr(node.operand)
            return f"(-{operand})" if node.op == '-' else f"(not {operand})"
        if isinstance(node, Assign):
            val = self.gen_expr(node.value)
            return f"({node.name} := {val})"
        if isinstance(node, IndexAccess):
            target = self.gen_expr(node.target)
            # Range slice: v[1..3]
            if isinstance(node.index, RangeLiteral):
                s = self.gen_expr(node.index.start)
                e = self.gen_expr(node.index.end)
                if node.index.inclusive:
                    return f"_fk_slice({target}, {s}, {e}, inclusive=True)"
                else:
                    return f"_fk_slice({target}, {s}, {e}, inclusive=False)"
            index = self.gen_expr(node.index)
            # Nil-safe access via helper (handles both dicts and lists)
            return f"_fk_index({target}, {index})"
        if isinstance(node, FuncCall):
            return self.gen_func_call(node)
        if isinstance(node, MethodCall):
            return self.gen_method_call(node)
        if isinstance(node, PipeOp):
            return self.gen_pipe(node)
        if isinstance(node, MatchOp):
            left = self.gen_expr(node.left)
            right = self.gen_expr(node.right)
            return f"_fk_match_op({left}, {right})"
        if isinstance(node, InputExpr):
            return self.gen_input(node)
        if isinstance(node, NamedArg):
            return f"{node.name}={self.gen_expr(node.value)}"
        raise CodeGenError(f"Unknown expression node: {type(node).__name__}")

    def gen_string(self, node: StringLiteral) -> str:
        """Build an f-string or plain string from parts."""
        parts = node.parts
        has_interp = any(kind == 'interp' for kind, _ in parts)
        if not has_interp:
            # Plain string
            s = "".join(v for _, v in parts)
            return repr(s)
        # f-string
        result = 'f"'
        for kind, val in parts:
            if kind == 'literal':
                result += val.replace('\\', '\\\\').replace('"', '\\"').replace('{', '{{').replace('}', '}}')
            else:
                # interp expression — parse and gen
                from .lexer import Lexer
                from .parser import Parser
                sub_tokens = Lexer(val.strip()).tokenize()
                sub_ast = Parser(sub_tokens).parse_expr()
                result += '{_fk_to_str(' + self.gen_expr(sub_ast) + ')}'
        result += '"'
        return result

    def gen_binop(self, node: BinOp) -> str:
        left = self.gen_expr(node.left)
        right = self.gen_expr(node.right)
        op_map = {
            '+': '+', '-': '-', '*': '*', '/': '/',
            '//': '//', '%': '%', '**': '**',
            '==': '==', '!=': '!=', '<': '<', '<=': '<=', '>': '>', '>=': '>=',
            'and': 'and', 'or': 'or',
        }
        py_op = op_map.get(node.op, node.op)

        # Vector-aware arithmetic: wrap in helper
        if node.op in ('+', '-', '*', '/', '//', '%', '**'):
            return f"_fk_arith({left!r}, {left}, {right!r}, {right}, {py_op!r})"

        return f"({left} {py_op} {right})"

    def gen_func_call(self, node: FuncCall) -> str:
        def gen_arg(a):
            if isinstance(a, NamedArg):
                return f"{a.name}={self.gen_expr(a.value)}"
            return self.gen_expr(a)
        args = ", ".join(gen_arg(a) for a in node.args)
        # Map built-in Frankie functions to runtime helpers
        stdlib_map = {
            'sum': '_fk_sum',
            'mean': '_fk_mean',
            'min': '_fk_min',
            'max': '_fk_max',
            'abs': '_fk_abs',
            'sqrt': '_fk_sqrt',
            'floor': '_fk_floor',
            'ceil': '_fk_ceil',
            'length': '_fk_length',
            'vec': '_fk_vec',
            'to_int': '_fk_to_int',
            'to_float': '_fk_to_float',
            'to_str': '_fk_to_str',
            'puts': 'print',
            'print': 'print',
        }
        py_name = stdlib_map.get(node.name, node.name)
        if node.name == 'print':
            return f"print(_fk_to_str({args}), end='')"
        if node.name == 'puts':
            return f"print(_fk_to_str({args}))"
        return f"{py_name}({args})"

    def gen_method_call(self, node: MethodCall) -> str:
        recv = self.gen_expr(node.receiver)

        # .times do |i| ... end
        if node.method == 'times':
            return self._gen_times(recv, node)

        # .each do |x| ... end  (or |k,v| for hashes)
        if node.method == 'each':
            return self._gen_each(recv, node)

        # .select do |x| ... end  — keep elements where block is true
        if node.method == 'select':
            return self._gen_block_method(recv, node, '_fk_select')

        # .reject do |x| ... end  — keep elements where block is false
        if node.method == 'reject':
            return self._gen_block_method(recv, node, '_fk_reject')

        # .reduce(init) do |acc, x| ... end
        if node.method == 'reduce' or node.method == 'inject':
            return self._gen_reduce(recv, node)

        # .each_with_object(obj) do |x, obj| ... end
        if node.method == 'each_with_object':
            return self._gen_each_with_object(recv, node)

        # .any? do |x| ... end
        if node.method == 'any?':
            return self._gen_predicate(recv, node, '_fk_any')

        # .all? do |x| ... end
        if node.method == 'all?':
            return self._gen_predicate(recv, node, '_fk_all')

        # .none? do |x| ... end
        if node.method == 'none?':
            return self._gen_predicate(recv, node, '_fk_none')

        # .count do |x| ... end  OR  .count("substr")  OR  .count (length)
        if node.method == 'count':
            if node.block:
                return self._gen_predicate(recv, node, '_fk_count_if')
            if node.args:
                arg = self.gen_expr(node.args[0])
                # Runtime dispatch: DB.count(table), str.count(sub), list len
                return f"_fk_count_dispatch({recv}, {arg})"
            return f"_fk_count_dispatch({recv})"

        # .sort_by do |x| ... end
        if node.method == 'sort_by':
            return self._gen_block_method(recv, node, '_fk_sort_by')

        # .min_by do |x| ... end
        if node.method == 'min_by':
            return self._gen_block_method(recv, node, '_fk_min_by')

        # .max_by do |x| ... end
        if node.method == 'max_by':
            return self._gen_block_method(recv, node, '_fk_max_by')

        # .sum_by do |x| ... end
        if node.method == 'sum_by':
            return self._gen_block_method(recv, node, '_fk_sum_by')

        # .find / .detect do |x| ... end  — return first matching element
        if node.method in ('find', 'detect'):
            return self._gen_block_method(recv, node, '_fk_find')

        # .flat_map do |x| ... end
        if node.method == 'flat_map':
            return self._gen_block_method(recv, node, '_fk_flat_map')

        # .take(n)
        if node.method == 'take':
            arg = self.gen_expr(node.args[0]) if node.args else '1'
            return f"_fk_take({recv}, {arg})"

        # .drop(n)
        if node.method == 'drop':
            arg = self.gen_expr(node.args[0]) if node.args else '1'
            return f"_fk_drop({recv}, {arg})"

        # .tally
        if node.method == 'tally':
            return f"_fk_tally({recv})"

        # .compact
        if node.method == 'compact':
            return f"_fk_compact({recv})"

        # .chunk(n)
        if node.method == 'chunk':
            arg = self.gen_expr(node.args[0]) if node.args else '2'
            return f"_fk_chunk({recv}, {arg})"

        # .zip(other)
        if node.method == 'zip':
            arg = self.gen_expr(node.args[0]) if node.args else '[]'
            return f"_fk_zip_vecs({recv}, {arg})"

        # .flatten
        if node.method == 'flatten':
            return f"_fk_flatten({recv})"

        # .each_with_index do |val, idx| ... end
        if node.method == 'each_with_index':
            return self._gen_each_with_index(recv, node)

        # .map do |x| ... end
        if node.method == 'map':
            return self._gen_map(recv, node)

        # String / vector methods
        method_map = {
            'upcase':    f"{recv}.upper()",
            'downcase':  f"{recv}.lower()",
            'length':    f"len({recv})",
            'reverse':   f"{recv}[::-1]",
            'strip':     f"{recv}.strip()",
            'lstrip':    f"{recv}.lstrip()",
            'rstrip':    f"{recv}.rstrip()",
            'to_i':      f"int({recv})",
            'to_f':      f"float({recv})",
            'to_s':      f"str({recv})",
            'chars':     f"_fk_chars({recv})",
            'lines':     f"_fk_lines({recv})",
            'chomp':     f"_fk_chomp({recv})",
            'chop':      f"_fk_chop({recv})",
            'ord':       f"_fk_ord({recv})",
            'first':     f"({recv}[0] if {recv} else None)",
            'last':      f"({recv}[-1] if {recv} else None)",
            'empty?':    f"(len({recv}) == 0)",
            'nil?':      f"({recv} is None)",
            'sort':      f"sorted({recv})",
            'uniq':      f"list(dict.fromkeys({recv}))",
            'flatten':   f"[_e for _sub in {recv} for _e in (_sub if isinstance(_sub, list) else [_sub])]",
            'sum':       f"_fk_sum({recv})",
            'min':       f"_fk_min({recv})",
            'max':       f"_fk_max({recv})",
            'mean':      f"_fk_mean({recv})",
        }

        if node.method in method_map:
            return method_map[node.method]

        # include? / start_with? / end_with?
        if node.method == 'include?':
            arg = self.gen_expr(node.args[0]) if node.args else '""'
            return f"({arg} in {recv})"
        if node.method == 'start_with?':
            arg = self.gen_expr(node.args[0]) if node.args else '""'
            return f"{recv}.startswith({arg})"
        if node.method == 'end_with?':
            arg = self.gen_expr(node.args[0]) if node.args else '""'
            return f"{recv}.endswith({arg})"
        if node.method == 'center':
            w = self.gen_expr(node.args[0]) if node.args else '0'
            p = self.gen_expr(node.args[1]) if len(node.args) > 1 else '" "'
            return f"_fk_center({recv}, {w}, {p})"
        if node.method == 'ljust':
            w = self.gen_expr(node.args[0]) if node.args else '0'
            p = self.gen_expr(node.args[1]) if len(node.args) > 1 else '" "'
            return f"_fk_ljust({recv}, {w}, {p})"
        if node.method == 'rjust':
            w = self.gen_expr(node.args[0]) if node.args else '0'
            p = self.gen_expr(node.args[1]) if len(node.args) > 1 else '" "'
            return f"_fk_rjust({recv}, {w}, {p})"
        if node.method == 'squeeze':
            arg = self.gen_expr(node.args[0]) if node.args else 'None'
            return f"_fk_squeeze({recv}, {arg})"
        if node.method == 'tr':
            fr = self.gen_expr(node.args[0]) if len(node.args) > 0 else '""'
            to = self.gen_expr(node.args[1]) if len(node.args) > 1 else '""'
            return f"_fk_tr({recv}, {fr}, {to})"
        if node.method == 'delete':
            # If there's a block, it's a web route: app.delete("/path") do |req| ... end
            if node.block:
                fn_name = self.temp_var("_route_fn")
                req_var = node.block.params[0] if node.block.params else '_req'
                self.emit(f"def {fn_name}({req_var}):")
                self.indent()
                self._gen_route_body(node.block.body)
                self.dedent()
                pattern = self.gen_expr(node.args[0]) if node.args else '"/"'
                return f"{recv}.delete({pattern}, {fn_name})"
            if not node.args:
                return f"{recv}.pop()"  # vector pop (no arg)
            if len(node.args) == 2:
                # DB.delete(table, where_hash) — two args means it's a DB call
                arg0 = self.gen_expr(node.args[0])
                arg1 = self.gen_expr(node.args[1])
                return f"{recv}.delete({arg0}, {arg1})"
            arg = self.gen_expr(node.args[0])
            # Single arg: str→delete chars, hash→pop key, vector→(not typical)
            return f"(_fk_str_delete({recv}, {arg}) if isinstance({recv}, str) else {recv}.pop({arg}, None))"
        if node.method == 'bytes':
            return f"_fk_bytes({recv})"
        if node.method == 'each_char':
            block = node.block
            if block:
                var = block.params[0] if block.params else '_c'
                self.emit(f"for {var} in {recv}:")
                self.indent()
                self.gen_body(block.body)
                self.dedent()
                return ""
            return f"_fk_chars({recv})"
        if node.method == 'each_line':
            block = node.block
            if block:
                var = block.params[0] if block.params else '_line'
                self.emit(f"for {var} in _fk_lines({recv}):")
                self.indent()
                self.gen_body(block.body)
                self.dedent()
                return ""
            return f"_fk_lines({recv})"
        if node.method == 'split':
            arg = self.gen_expr(node.args[0]) if node.args else '" "'
            return f"{recv}.split({arg})"
        if node.method == 'join':
            arg = self.gen_expr(node.args[0]) if node.args else '""'
            return f"{arg}.join([str(_e) for _e in {recv}])"
        if node.method == 'push':
            arg = self.gen_expr(node.args[0]) if node.args else 'None'
            return f"(_fk_list_push({recv}, {arg}))"
        if node.method == 'pop':
            return f"{recv}.pop()"
        if node.method == 'keys':
            return f"list({recv}.keys())"
        if node.method == 'values':
            return f"list({recv}.values())"
        if node.method == 'has_key?':
            arg = self.gen_expr(node.args[0]) if node.args else '""'
            return f"({arg} in {recv})"
        if node.method == 'merge':
            arg = self.gen_expr(node.args[0]) if node.args else '{}'
            return "{" + f"**{recv}, **{arg}" + "}"
        if node.method == 'merge_bang':
            arg = self.gen_expr(node.args[0]) if node.args else '{}'
            return f"(_fk_hash_merge_bang({recv}, {arg}))"
        if node.method in ('size', 'count'):
            return f"len({recv})"
        if node.method == 'to_a':
            return f"list({recv}.items())"
        if node.method == 'each_pair':
            block = node.block
            if block is None:
                return f"list({recv}.items())"
            k_var = block.params[0] if len(block.params) > 0 else '_k'
            v_var = block.params[1] if len(block.params) > 1 else '_v'
            self.emit(f"for {k_var}, {v_var} in {recv}.items():")
            self.indent()
            self.gen_body(block.body)
            self.dedent()
            return ""
        if node.method == 'each':
            block = node.block
            if block and len(block.params) == 2:
                k_var, v_var = block.params[0], block.params[1]
                self.emit(f"for {k_var}, {v_var} in {recv}.items():")
                self.indent()
                self.gen_body(block.body)
                self.dedent()
                return ""
            elif block and len(block.params) == 1:
                pair_var = block.params[0]
                self.emit(f"for {pair_var} in {recv}.items():")
                self.indent()
                self.gen_body(block.body)
                self.dedent()
                return ""
            return f"list({recv}.items())"
        if node.method == 'fetch':
            arg = self.gen_expr(node.args[0]) if node.args else '""'
            default = self.gen_expr(node.args[1]) if len(node.args) > 1 else 'None'
            return f"{recv}.get({arg}, {default})"
        if node.method == 'store':
            k = self.gen_expr(node.args[0]) if len(node.args) > 0 else '""'
            v = self.gen_expr(node.args[1]) if len(node.args) > 1 else 'None'
            return f"(_fk_hash_store({recv}, {k}, {v}))"

        # ── Property accessors (no parens) ─────────────────────────────────────
        # DateTime + HTTP response + FrankieRequest attributes
        if node.method in ('year','month','day','hour','minute','second',
                           'status','body','headers','content_type',
                           'params','query','form','path','method'):
            return f"{recv}.{node.method}"

        # .json is a property on FrankieRequest but a method on HTTP responses.
        # With no args and no block, treat it as a property (req.json).
        if node.method == 'json' and not node.args and not node.block:
            return f"{recv}.json"

        # ── DateTime methods ──────────────────────────────────────────────────
        if node.method == 'format':
            arg = self.gen_expr(node.args[0]) if node.args else '"%Y-%m-%d %H:%M:%S"'
            return f"{recv}.format({arg})"
        if node.method == 'add_days':
            arg = self.gen_expr(node.args[0]) if node.args else '1'
            return f"{recv}.add_days({arg})"
        if node.method == 'add_hours':
            arg = self.gen_expr(node.args[0]) if node.args else '1'
            return f"{recv}.add_hours({arg})"
        if node.method == 'add_minutes':
            arg = self.gen_expr(node.args[0]) if node.args else '1'
            return f"{recv}.add_minutes({arg})"
        if node.method == 'diff_days':
            arg = self.gen_expr(node.args[0]) if node.args else 'None'
            return f"{recv}.diff_days({arg})"
        if node.method == 'diff_seconds':
            arg = self.gen_expr(node.args[0]) if node.args else 'None'
            return f"{recv}.diff_seconds({arg})"
        if node.method == 'weekday':
            return f"{recv}.weekday()"
        if node.method == 'weekday_name':
            return f"{recv}.weekday_name()"
        if node.method == 'is_before':
            arg = self.gen_expr(node.args[0]) if node.args else 'None'
            return f"{recv}.is_before({arg})"
        if node.method == 'is_after':
            arg = self.gen_expr(node.args[0]) if node.args else 'None'
            return f"{recv}.is_after({arg})"
        if node.method == 'timestamp':
            return f"{recv}.timestamp()"
        if node.method == 'to_s':
            return f"_fk_to_str({recv})"

        # ── HTTP response methods ─────────────────────────────────────────────
        if node.method == 'json':
            return f"{recv}.json()"
        if node.method == 'ok':
            if not node.args and not node.block:
                return f"{recv}.ok()"

        # ── Database methods ──────────────────────────────────────────────────
        # transaction do ... end  — wraps body in begin/commit/rollback
        if node.method == 'transaction':
            block = node.block
            if block:
                self.emit("try:")
                self.indent()
                self.emit(f"{recv}.begin()")
                self.gen_body(block.body)
                self.emit(f"{recv}.commit()")
                self.dedent()
                self.emit("except Exception as _tx_err:")
                self.indent()
                self.emit(f"{recv}.rollback()")
                self.emit("raise _tx_err")
                self.dedent()
                return ""
            return f"{recv}.begin()"

        # ── Web app route/filter registration ────────────────────────────────
        # app.get("/path") do |req| ... end
        # app.post / put / delete / patch / before / after / not_found
        if node.method in ('get', 'post', 'put', 'delete', 'patch',
                           'before', 'after', 'not_found'):
            block = node.block
            if block:
                # Emit a named handler function then pass it as an argument
                fn_name  = self.temp_var("_route_fn")
                req_var  = block.params[0] if block.params else '_req'
                # after-filter receives (req, res)
                if node.method == 'after' and len(block.params) >= 2:
                    req_var = f"{block.params[0]}, {block.params[1]}"
                self.emit(f"def {fn_name}({req_var}):")
                self.indent()
                self._gen_route_body(block.body)
                self.dedent()
                # after/before/not_found take only the handler
                if node.method in ('before', 'after', 'not_found'):
                    return f"{recv}.{node.method}({fn_name})"
                # route methods take (pattern, handler)
                pattern = self.gen_expr(node.args[0]) if node.args else '"/..."'
                return f"{recv}.{node.method}({pattern}, {fn_name})"
            # No block — plain call (e.g. programmatic registration)
            args = ", ".join(self.gen_expr(a) for a in node.args)
            return f"{recv}.{node.method}({args})"

        # ── web app .run(port) ────────────────────────────────────────────────
        if node.method == 'run' and not node.block:
            args = ", ".join(self.gen_expr(a) for a in node.args)
            return f"{recv}.run({args})"

        # Generic fallback — handles all other method calls including
        # DB methods: exec, query, query_one, insert, insert_many,
        # find_all, find, find_one, update, delete, count, tables,
        # columns, last_id, begin, commit, rollback, close
        args = ", ".join(self.gen_expr(a) for a in node.args)
        return f"{recv}.{node.method}({args})"

    def _gen_times(self, recv, node: MethodCall) -> str:
        """Generate a for loop for N.times do |i| ... end"""
        block = node.block
        if block is None:
            return f"_fk_times({recv}, lambda: None)"
        var = block.params[0] if block.params else '_'
        # Can't return expr for a loop — emit statements instead
        self.emit(f"for {var} in range({recv}):")
        self.indent()
        self.gen_body(block.body)
        self.dedent()
        return ""

    def _gen_each(self, recv, node: MethodCall) -> str:
        block = node.block
        if block is None:
            return f"_fk_each({recv})"
        # Two params → hash iteration: do |key, val|
        if len(block.params) == 2:
            k_var, v_var = block.params[0], block.params[1]
            self.emit(f"for {k_var}, {v_var} in ({recv}.items() if isinstance({recv}, dict) else enumerate({recv})):")
            self.indent()
            self.gen_body(block.body)
            self.dedent()
            return ""
        var = block.params[0] if block.params else '_'
        self.emit(f"for {var} in {recv}:")
        self.indent()
        self.gen_body(block.body)
        self.dedent()
        return ""

    def _gen_each_with_index(self, recv, node: MethodCall) -> str:
        block = node.block
        if block is None:
            return f"_fk_each_with_index({recv})"
        val_var = block.params[0] if len(block.params) > 0 else '_v'
        idx_var = block.params[1] if len(block.params) > 1 else '_i'
        self.emit(f"for {idx_var}, {val_var} in enumerate({recv}):")
        self.indent()
        self.gen_body(block.body)
        self.dedent()
        return ""

    def _gen_map(self, recv, node: MethodCall) -> str:
        block = node.block
        if block is None:
            return f"list({recv})"
        var = block.params[0] if block.params else '_'
        # map returns a value — use list comprehension
        if len(block.body) == 1:
            body_expr = self.gen_expr(block.body[0])
            return f"[{body_expr} for {var} in {recv}]"
        # Multi-statement map: use lambda with walrus / helper
        # For simplicity, emit as a separate function
        fn_name = self.temp_var("_map_fn")
        self.emit(f"def {fn_name}({var}):")
        self.indent()
        for stmt in block.body[:-1]:
            self.gen_stmt(stmt)
        last = self.gen_expr(block.body[-1])
        self.emit(f"return {last}")
        self.dedent()
        return f"[{fn_name}({var}) for {var} in {recv}]"

    def _block_to_lambda(self, block, recv) -> str:
        """Convert a single-expression block to a Python lambda string."""
        var = block.params[0] if block.params else '_'
        if len(block.body) == 1:
            body_expr = self.gen_expr(block.body[0])
            return f"lambda {var}: {body_expr}"
        # Multi-statement: emit a helper function and return its name
        fn_name = self.temp_var("_blk_fn")
        self.emit(f"def {fn_name}({var}):")
        self.indent()
        for stmt in block.body[:-1]:
            self.gen_stmt(stmt)
        last = self.gen_expr(block.body[-1])
        self.emit(f"return {last}")
        self.dedent()
        return fn_name

    def _gen_block_method(self, recv, node: MethodCall, helper: str) -> str:
        """Generate: helper(recv, lambda x: body)"""
        block = node.block
        if block is None:
            return f"{helper}({recv}, lambda x: x)"
        lam = self._block_to_lambda(block, recv)
        return f"{helper}({recv}, {lam})"

    def _gen_predicate(self, recv, node: MethodCall, helper: str) -> str:
        """Generate: helper(recv, lambda x: body)"""
        block = node.block
        if block is None:
            return f"{helper}({recv})"
        lam = self._block_to_lambda(block, recv)
        return f"{helper}({recv}, {lam})"

    def _gen_reduce(self, recv, node: MethodCall) -> str:
        """Generate reduce/inject with optional initial value and block."""
        block = node.block
        initial = self.gen_expr(node.args[0]) if node.args else 'None'
        if block is None:
            return f"_fk_reduce({recv}, lambda a, b: a + b, {initial})"
        params = block.params if block.params else ['_acc', '_x']
        acc_var = params[0] if len(params) > 0 else '_acc'
        x_var   = params[1] if len(params) > 1 else '_x'
        if len(block.body) == 1:
            body_expr = self.gen_expr(block.body[0])
            lam = f"lambda {acc_var}, {x_var}: {body_expr}"
        else:
            fn_name = self.temp_var("_reduce_fn")
            self.emit(f"def {fn_name}({acc_var}, {x_var}):")
            self.indent()
            for stmt in block.body[:-1]:
                self.gen_stmt(stmt)
            last = self.gen_expr(block.body[-1])
            self.emit(f"return {last}")
            self.dedent()
            lam = fn_name
        return f"_fk_reduce({recv}, {lam}, {initial})"

    def _gen_each_with_object(self, recv, node: MethodCall) -> str:
        """Generate each_with_object(init) do |x, obj| ... end"""
        block = node.block
        init = self.gen_expr(node.args[0]) if node.args else '[]'
        if block is None:
            return f"_fk_each_with_object({recv}, {init}, lambda x, o: None)"
        x_var   = block.params[0] if len(block.params) > 0 else '_x'
        obj_var = block.params[1] if len(block.params) > 1 else '_obj'
        obj_tmp = self.temp_var("_ewo_obj")
        self.emit(f"{obj_tmp} = {init}")
        self.emit(f"for {x_var} in {recv}:")
        self.indent()
        # bind obj_var to obj_tmp inside the loop
        self.emit(f"{obj_var} = {obj_tmp}")
        self.gen_body(block.body)
        self.dedent()
        return obj_tmp

    def gen_break(self, node):
        """break / break value"""
        if node.value is None:
            self.emit("break")
        else:
            # Python doesn't support break-with-value natively.
            # Use a sentinel variable pattern: _fk_break_val = expr; break
            val = self.gen_expr(node.value)
            self.emit(f"_fk_break_val = {val}")
            self.emit("break")

    def gen_const_assign(self, node):
        """UPPER_CASE = value — warn on reassignment via _fk_const_set"""
        val = self.gen_expr(node.value)
        self.emit(f"{node.name} = _fk_const_set({node.name!r}, {val})")

    def _gen_route_body(self, body):
        """
        Emit a route/filter handler body.
        Unlike gen_body, the last expression statement is wrapped in `return`
        so that response helpers like response(), json_response(), halt() etc.
        are returned to the dispatcher rather than discarded.
        """
        # Nodes that are pure control-flow and should NOT be auto-returned
        _no_return = (FuncDef, IfStmt, UnlessStmt, WhileStmt, UntilStmt,
                      DoWhileStmt, ForInStmt, ReturnStmt, BeginRescue,
                      CaseStmt, PrintStmt, DebugPrint)
        if not body:
            self.emit("pass")
            return
        for stmt in body[:-1]:
            self.gen_stmt(stmt)
        last = body[-1]
        if isinstance(last, ReturnStmt):
            # Already an explicit return — emit normally
            self.gen_stmt(last)
        elif isinstance(last, _no_return):
            # Control flow at the end: emit as-is (handler returns None -> empty 200)
            self.gen_stmt(last)
        else:
            # Expression statement — emit as `return <expr>`
            expr = self.gen_expr(last)
            self.emit(f"return {expr}")

    def gen_pipe(self, node: PipeOp) -> str:
        left = self.gen_expr(node.left)
        if isinstance(node.right, Identifier):
            # simple function name
            stdlib_map = {
                'sum': '_fk_sum', 'mean': '_fk_mean', 'min': '_fk_min',
                'max': '_fk_max', 'abs': '_fk_abs', 'sqrt': '_fk_sqrt',
                'floor': '_fk_floor', 'ceil': '_fk_ceil', 'length': '_fk_length',
                'to_str': '_fk_to_str', 'to_int': '_fk_to_int',
                'puts': 'print', 'print': 'print',
            }
            fn = stdlib_map.get(node.right.name, node.right.name)
            if fn == 'print':
                return f"print(_fk_to_str({left}), end='')"
            if fn == 'puts':
                return f"print(_fk_to_str({left}))"
            return f"{fn}({left})"
        if isinstance(node.right, FuncCall):
            args_str = ", ".join(self.gen_expr(a) for a in node.right.args)
            all_args = f"{left}, {args_str}" if args_str else left
            return f"{node.right.name}({all_args})"
        right = self.gen_expr(node.right)
        return f"{right}({left})"

    def gen_input(self, node: InputExpr) -> str:
        if node.prompt:
            prompt = self.gen_expr(node.prompt)
            raw = f"input({prompt})"
        else:
            raw = "input()"
        if node.cast == 'int':
            return f"int({raw})"
        if node.cast == 'float':
            return f"float({raw})"
        return raw

    # Map Frankie type names → Python exception classes (zero-dep, no import needed)
    _RESCUE_TYPE_MAP = {
        'RuntimeError':    'RuntimeError',
        'TypeError':       'TypeError',
        'ValueError':      'ValueError',
        'ZeroDivisionError': 'ZeroDivisionError',
        'IndexError':      'IndexError',
        'KeyError':        'KeyError',
        'IOError':         'IOError',
        'FileNotFoundError': 'FileNotFoundError',
        'OverflowError':   'OverflowError',
        'NameError':       'NameError',
        'AttributeError':  'AttributeError',
        'StopIteration':   'StopIteration',
        'Exception':       'Exception',
        'Error':           'Exception',   # alias
    }

    def gen_begin_rescue(self, node):
        self.emit("try:")
        self.indent()
        self.gen_body(node.body)
        self.dedent()
        clauses = node.rescue_clauses
        for i, clause in enumerate(clauses):
            exc_class = self._RESCUE_TYPE_MAP.get(clause.error_type, 'Exception') if clause.error_type else 'Exception'
            tmp = clause.rescue_var or '_fk_err'
            self.emit(f"except {exc_class} as {tmp}:")
            self.indent()
            if clause.body:
                if clause.rescue_var:
                    self.emit(f"{clause.rescue_var} = str({clause.rescue_var})")
                self.gen_body(clause.body)
            else:
                self.emit("pass")
            self.dedent()
        if node.ensure_body:
            self.emit("finally:")
            self.indent()
            self.gen_body(node.ensure_body)
            self.dedent()

    def gen_raise(self, node):
        if node.message:
            msg = self.gen_expr(node.message)
            self.emit(f"raise RuntimeError(_fk_to_str({msg}))")
        else:
            self.emit("raise")

    def gen_require(self, node):
        path = self.gen_expr(node.path)
        self.emit(f"_fk_require({path})")

    def gen_case(self, node):
        if node.subject is not None:
            subj = self.gen_expr(node.subject)
            subj_tmp = self.temp_var("_case")
            self.emit(f"{subj_tmp} = {subj}")
        first = True
        for values, body in node.when_clauses:
            if node.subject is not None:
                cond_parts = [f"({subj_tmp} == {self.gen_expr(v)})" for v in values]
                cond = " or ".join(cond_parts)
            else:
                # bare case: when condition (truthy)
                cond_parts = [self.gen_expr(v) for v in values]
                cond = " or ".join(cond_parts)
            kw = "if" if first else "elif"
            self.emit(f"{kw} {cond}:")
            self.indent()
            self.gen_body(body)
            self.dedent()
            first = False
        if node.else_body is not None:
            self.emit("else:")
            self.indent()
            self.gen_body(node.else_body)
            self.dedent()

    def gen_destruct_assign(self, node):
        value = self.gen_expr(node.value)
        names = ", ".join(node.names)
        # Use Python iterable unpacking
        self.emit(f"{names} = _fk_unpack({value}, {len(node.names)})")
